// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface ActionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.ActionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 Time = 1;</code>
   */
  int getTime();

  /**
   * <code>string User = 2;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string User = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>uint32 DeviceID = 3;</code>
   */
  int getDeviceID();

  /**
   * <code>uint32 ErrorCode = 4;</code>
   */
  int getErrorCode();

  /**
   * <code>string Action = 5;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string Action = 5;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData();
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getDataMap();
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  com.google.protobuf.ByteString getDataOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  com.google.protobuf.ByteString getDataOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */
  int getData2Count();
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */
  boolean containsData2(
      java.lang.String key);
  /**
   * Use {@link #getData2Map()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData2();
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData2Map();
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  com.google.protobuf.ByteString getData2OrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  com.google.protobuf.ByteString getData2OrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */
  int getData3Count();
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */
  boolean containsData3(
      java.lang.String key);
  /**
   * Use {@link #getData3Map()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData3();
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getData3Map();
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  com.google.protobuf.ByteString getData3OrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  com.google.protobuf.ByteString getData3OrThrow(
      java.lang.String key);
}
