// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.ActionResponse}
 */
public  final class ActionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.ActionResponse)
    ActionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActionResponse.newBuilder() to construct.
  private ActionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionResponse() {
    time_ = 0;
    user_ = "";
    deviceID_ = 0;
    errorCode_ = 0;
    action_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            user_ = s;
            break;
          }
          case 24: {

            deviceID_ = input.readUInt32();
            break;
          }
          case 32: {

            errorCode_ = input.readUInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              data_ = com.google.protobuf.MapField.newMapField(
                  DataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            data__ = input.readMessage(
                DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            data_.getMutableMap().put(
                data__.getKey(), data__.getValue());
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              data2_ = com.google.protobuf.MapField.newMapField(
                  Data2DefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            data2__ = input.readMessage(
                Data2DefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            data2_.getMutableMap().put(
                data2__.getKey(), data2__.getValue());
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              data3_ = com.google.protobuf.MapField.newMapField(
                  Data3DefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000080;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            data3__ = input.readMessage(
                Data3DefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            data3_.getMutableMap().put(
                data3__.getKey(), data3__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetData();
      case 7:
        return internalGetData2();
      case 8:
        return internalGetData3();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.ActionResponse.class, net.anysync.protoc.ActionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_FIELD_NUMBER = 1;
  private int time_;
  /**
   * <code>uint32 Time = 1;</code>
   */
  public int getTime() {
    return time_;
  }

  public static final int USER_FIELD_NUMBER = 2;
  private volatile java.lang.Object user_;
  /**
   * <code>string User = 2;</code>
   */
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string User = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 3;
  private int deviceID_;
  /**
   * <code>uint32 DeviceID = 3;</code>
   */
  public int getDeviceID() {
    return deviceID_;
  }

  public static final int ERRORCODE_FIELD_NUMBER = 4;
  private int errorCode_;
  /**
   * <code>uint32 ErrorCode = 4;</code>
   */
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int ACTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object action_;
  /**
   * <code>string Action = 5;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string Action = 5;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private static final class DataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_DataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> data_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetData() {
    if (data_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DataDefaultEntryHolder.defaultEntry);
    }
    return data_;
  }

  public int getDataCount() {
    return internalGetData().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  public boolean containsData(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData() {
    return getDataMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getDataMap() {
    return internalGetData().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  public com.google.protobuf.ByteString getDataOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Data = 6;</code>
   */

  public com.google.protobuf.ByteString getDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DATA2_FIELD_NUMBER = 7;
  private static final class Data2DefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_Data2Entry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> data2_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetData2() {
    if (data2_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          Data2DefaultEntryHolder.defaultEntry);
    }
    return data2_;
  }

  public int getData2Count() {
    return internalGetData2().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  public boolean containsData2(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetData2().getMap().containsKey(key);
  }
  /**
   * Use {@link #getData2Map()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData2() {
    return getData2Map();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData2Map() {
    return internalGetData2().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  public com.google.protobuf.ByteString getData2OrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData2().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
   */

  public com.google.protobuf.ByteString getData2OrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData2().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DATA3_FIELD_NUMBER = 8;
  private static final class Data3DefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_Data3Entry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> data3_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetData3() {
    if (data3_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          Data3DefaultEntryHolder.defaultEntry);
    }
    return data3_;
  }

  public int getData3Count() {
    return internalGetData3().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  public boolean containsData3(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetData3().getMap().containsKey(key);
  }
  /**
   * Use {@link #getData3Map()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData3() {
    return getData3Map();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData3Map() {
    return internalGetData3().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  public com.google.protobuf.ByteString getData3OrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData3().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
   */

  public com.google.protobuf.ByteString getData3OrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetData3().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0) {
      output.writeUInt32(1, time_);
    }
    if (!getUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
    }
    if (deviceID_ != 0) {
      output.writeUInt32(3, deviceID_);
    }
    if (errorCode_ != 0) {
      output.writeUInt32(4, errorCode_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, action_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetData(),
        DataDefaultEntryHolder.defaultEntry,
        6);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetData2(),
        Data2DefaultEntryHolder.defaultEntry,
        7);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetData3(),
        Data3DefaultEntryHolder.defaultEntry,
        8);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, time_);
    }
    if (!getUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
    }
    if (deviceID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, deviceID_);
    }
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, errorCode_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, action_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, data__);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetData2().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      data2__ = Data2DefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, data2__);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetData3().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      data3__ = Data3DefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, data3__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.ActionResponse)) {
      return super.equals(obj);
    }
    net.anysync.protoc.ActionResponse other = (net.anysync.protoc.ActionResponse) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && getUser()
        .equals(other.getUser());
    result = result && (getDeviceID()
        == other.getDeviceID());
    result = result && (getErrorCode()
        == other.getErrorCode());
    result = result && getAction()
        .equals(other.getAction());
    result = result && internalGetData().equals(
        other.internalGetData());
    result = result && internalGetData2().equals(
        other.internalGetData2());
    result = result && internalGetData3().equals(
        other.internalGetData3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceID();
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    if (!internalGetData().getMap().isEmpty()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetData().hashCode();
    }
    if (!internalGetData2().getMap().isEmpty()) {
      hash = (37 * hash) + DATA2_FIELD_NUMBER;
      hash = (53 * hash) + internalGetData2().hashCode();
    }
    if (!internalGetData3().getMap().isEmpty()) {
      hash = (37 * hash) + DATA3_FIELD_NUMBER;
      hash = (53 * hash) + internalGetData3().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.ActionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ActionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ActionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.ActionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.ActionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.ActionResponse)
      net.anysync.protoc.ActionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetData();
        case 7:
          return internalGetData2();
        case 8:
          return internalGetData3();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableData();
        case 7:
          return internalGetMutableData2();
        case 8:
          return internalGetMutableData3();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.ActionResponse.class, net.anysync.protoc.ActionResponse.Builder.class);
    }

    // Construct using net.anysync.protoc.ActionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0;

      user_ = "";

      deviceID_ = 0;

      errorCode_ = 0;

      action_ = "";

      internalGetMutableData().clear();
      internalGetMutableData2().clear();
      internalGetMutableData3().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ActionResponse_descriptor;
    }

    public net.anysync.protoc.ActionResponse getDefaultInstanceForType() {
      return net.anysync.protoc.ActionResponse.getDefaultInstance();
    }

    public net.anysync.protoc.ActionResponse build() {
      net.anysync.protoc.ActionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.ActionResponse buildPartial() {
      net.anysync.protoc.ActionResponse result = new net.anysync.protoc.ActionResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.time_ = time_;
      result.user_ = user_;
      result.deviceID_ = deviceID_;
      result.errorCode_ = errorCode_;
      result.action_ = action_;
      result.data_ = internalGetData();
      result.data_.makeImmutable();
      result.data2_ = internalGetData2();
      result.data2_.makeImmutable();
      result.data3_ = internalGetData3();
      result.data3_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.ActionResponse) {
        return mergeFrom((net.anysync.protoc.ActionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.ActionResponse other) {
      if (other == net.anysync.protoc.ActionResponse.getDefaultInstance()) return this;
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      if (other.getDeviceID() != 0) {
        setDeviceID(other.getDeviceID());
      }
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      internalGetMutableData().mergeFrom(
          other.internalGetData());
      internalGetMutableData2().mergeFrom(
          other.internalGetData2());
      internalGetMutableData3().mergeFrom(
          other.internalGetData3());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.ActionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.ActionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int time_ ;
    /**
     * <code>uint32 Time = 1;</code>
     */
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 Time = 1;</code>
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object user_ = "";
    /**
     * <code>string User = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string User = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string User = 2;</code>
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string User = 2;</code>
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string User = 2;</code>
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private int deviceID_ ;
    /**
     * <code>uint32 DeviceID = 3;</code>
     */
    public int getDeviceID() {
      return deviceID_;
    }
    /**
     * <code>uint32 DeviceID = 3;</code>
     */
    public Builder setDeviceID(int value) {
      
      deviceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 DeviceID = 3;</code>
     */
    public Builder clearDeviceID() {
      
      deviceID_ = 0;
      onChanged();
      return this;
    }

    private int errorCode_ ;
    /**
     * <code>uint32 ErrorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <code>uint32 ErrorCode = 4;</code>
     */
    public Builder setErrorCode(int value) {
      
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 ErrorCode = 4;</code>
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string Action = 5;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Action = 5;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Action = 5;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Action = 5;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string Action = 5;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> data_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableData() {
      onChanged();;
      if (data_ == null) {
        data_ = com.google.protobuf.MapField.newMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      if (!data_.isMutable()) {
        data_ = data_.copy();
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public com.google.protobuf.ByteString getDataOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public com.google.protobuf.ByteString getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearData() {
      internalGetMutableData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public Builder removeData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableData() {
      return internalGetMutableData().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */
    public Builder putData(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data = 6;</code>
     */

    public Builder putAllData(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableData().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> data2_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetData2() {
      if (data2_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            Data2DefaultEntryHolder.defaultEntry);
      }
      return data2_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableData2() {
      onChanged();;
      if (data2_ == null) {
        data2_ = com.google.protobuf.MapField.newMapField(
            Data2DefaultEntryHolder.defaultEntry);
      }
      if (!data2_.isMutable()) {
        data2_ = data2_.copy();
      }
      return data2_;
    }

    public int getData2Count() {
      return internalGetData2().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public boolean containsData2(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetData2().getMap().containsKey(key);
    }
    /**
     * Use {@link #getData2Map()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData2() {
      return getData2Map();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData2Map() {
      return internalGetData2().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public com.google.protobuf.ByteString getData2OrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData2().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public com.google.protobuf.ByteString getData2OrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData2().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearData2() {
      internalGetMutableData2().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public Builder removeData2(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData2().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableData2() {
      return internalGetMutableData2().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */
    public Builder putData2(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData2().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data2 = 7;</code>
     */

    public Builder putAllData2(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableData2().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> data3_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetData3() {
      if (data3_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            Data3DefaultEntryHolder.defaultEntry);
      }
      return data3_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableData3() {
      onChanged();;
      if (data3_ == null) {
        data3_ = com.google.protobuf.MapField.newMapField(
            Data3DefaultEntryHolder.defaultEntry);
      }
      if (!data3_.isMutable()) {
        data3_ = data3_.copy();
      }
      return data3_;
    }

    public int getData3Count() {
      return internalGetData3().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public boolean containsData3(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetData3().getMap().containsKey(key);
    }
    /**
     * Use {@link #getData3Map()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData3() {
      return getData3Map();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getData3Map() {
      return internalGetData3().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public com.google.protobuf.ByteString getData3OrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData3().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public com.google.protobuf.ByteString getData3OrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetData3().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearData3() {
      internalGetMutableData3().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public Builder removeData3(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData3().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableData3() {
      return internalGetMutableData3().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */
    public Builder putData3(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData3().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Data3 = 8;</code>
     */

    public Builder putAllData3(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableData3().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.ActionResponse)
  }

  // @@protoc_insertion_point(class_scope:utils.ActionResponse)
  private static final net.anysync.protoc.ActionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.ActionResponse();
  }

  public static net.anysync.protoc.ActionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ActionResponse>() {
    public ActionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionResponse> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.ActionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

