// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.BinLogResponse}
 */
public  final class BinLogResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.BinLogResponse)
    BinLogResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinLogResponse.newBuilder() to construct.
  private BinLogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinLogResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BinLogResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              folderUpdates_ = com.google.protobuf.MapField.newMapField(
                  FolderUpdatesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
            folderUpdates__ = input.readMessage(
                FolderUpdatesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            folderUpdates_.getMutableMap().put(
                folderUpdates__.getKey(), folderUpdates__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              serverChanges_ = com.google.protobuf.MapField.newMapField(
                  ServerChangesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ModifiedFolder>
            serverChanges__ = input.readMessage(
                ServerChangesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            serverChanges_.getMutableMap().put(
                serverChanges__.getKey(), serverChanges__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFolderUpdates();
      case 2:
        return internalGetServerChanges();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.BinLogResponse.class, net.anysync.protoc.BinLogResponse.Builder.class);
  }

  public static final int FOLDERUPDATES_FIELD_NUMBER = 1;
  private static final class FolderUpdatesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, net.anysync.protoc.ServerFolderUpdates> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, net.anysync.protoc.ServerFolderUpdates>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_FolderUpdatesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                net.anysync.protoc.ServerFolderUpdates.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, net.anysync.protoc.ServerFolderUpdates> folderUpdates_;
  private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  internalGetFolderUpdates() {
    if (folderUpdates_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FolderUpdatesDefaultEntryHolder.defaultEntry);
    }
    return folderUpdates_;
  }

  public int getFolderUpdatesCount() {
    return internalGetFolderUpdates().getMap().size();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  public boolean containsFolderUpdates(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetFolderUpdates().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFolderUpdatesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdates() {
    return getFolderUpdatesMap();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdatesMap() {
    return internalGetFolderUpdates().getMap();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ServerFolderUpdates defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
        internalGetFolderUpdates().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
        internalGetFolderUpdates().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SERVERCHANGES_FIELD_NUMBER = 2;
  private static final class ServerChangesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, net.anysync.protoc.ModifiedFolder> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, net.anysync.protoc.ModifiedFolder>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_ServerChangesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                net.anysync.protoc.ModifiedFolder.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, net.anysync.protoc.ModifiedFolder> serverChanges_;
  private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ModifiedFolder>
  internalGetServerChanges() {
    if (serverChanges_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ServerChangesDefaultEntryHolder.defaultEntry);
    }
    return serverChanges_;
  }

  public int getServerChangesCount() {
    return internalGetServerChanges().getMap().size();
  }
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  public boolean containsServerChanges(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetServerChanges().getMap().containsKey(key);
  }
  /**
   * Use {@link #getServerChangesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> getServerChanges() {
    return getServerChangesMap();
  }
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  public java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> getServerChangesMap() {
    return internalGetServerChanges().getMap();
  }
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  public net.anysync.protoc.ModifiedFolder getServerChangesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ModifiedFolder defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> map =
        internalGetServerChanges().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  public net.anysync.protoc.ModifiedFolder getServerChangesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> map =
        internalGetServerChanges().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFolderUpdates(),
        FolderUpdatesDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetServerChanges(),
        ServerChangesDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, net.anysync.protoc.ServerFolderUpdates> entry
         : internalGetFolderUpdates().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
      folderUpdates__ = FolderUpdatesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, folderUpdates__);
    }
    for (java.util.Map.Entry<java.lang.String, net.anysync.protoc.ModifiedFolder> entry
         : internalGetServerChanges().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ModifiedFolder>
      serverChanges__ = ServerChangesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serverChanges__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.BinLogResponse)) {
      return super.equals(obj);
    }
    net.anysync.protoc.BinLogResponse other = (net.anysync.protoc.BinLogResponse) obj;

    boolean result = true;
    result = result && internalGetFolderUpdates().equals(
        other.internalGetFolderUpdates());
    result = result && internalGetServerChanges().equals(
        other.internalGetServerChanges());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFolderUpdates().getMap().isEmpty()) {
      hash = (37 * hash) + FOLDERUPDATES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFolderUpdates().hashCode();
    }
    if (!internalGetServerChanges().getMap().isEmpty()) {
      hash = (37 * hash) + SERVERCHANGES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetServerChanges().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.BinLogResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.BinLogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.BinLogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.BinLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.BinLogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.BinLogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.BinLogResponse)
      net.anysync.protoc.BinLogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFolderUpdates();
        case 2:
          return internalGetServerChanges();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFolderUpdates();
        case 2:
          return internalGetMutableServerChanges();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.BinLogResponse.class, net.anysync.protoc.BinLogResponse.Builder.class);
    }

    // Construct using net.anysync.protoc.BinLogResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableFolderUpdates().clear();
      internalGetMutableServerChanges().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_BinLogResponse_descriptor;
    }

    public net.anysync.protoc.BinLogResponse getDefaultInstanceForType() {
      return net.anysync.protoc.BinLogResponse.getDefaultInstance();
    }

    public net.anysync.protoc.BinLogResponse build() {
      net.anysync.protoc.BinLogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.BinLogResponse buildPartial() {
      net.anysync.protoc.BinLogResponse result = new net.anysync.protoc.BinLogResponse(this);
      int from_bitField0_ = bitField0_;
      result.folderUpdates_ = internalGetFolderUpdates();
      result.folderUpdates_.makeImmutable();
      result.serverChanges_ = internalGetServerChanges();
      result.serverChanges_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.BinLogResponse) {
        return mergeFrom((net.anysync.protoc.BinLogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.BinLogResponse other) {
      if (other == net.anysync.protoc.BinLogResponse.getDefaultInstance()) return this;
      internalGetMutableFolderUpdates().mergeFrom(
          other.internalGetFolderUpdates());
      internalGetMutableServerChanges().mergeFrom(
          other.internalGetServerChanges());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.BinLogResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.BinLogResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, net.anysync.protoc.ServerFolderUpdates> folderUpdates_;
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    internalGetFolderUpdates() {
      if (folderUpdates_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FolderUpdatesDefaultEntryHolder.defaultEntry);
      }
      return folderUpdates_;
    }
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    internalGetMutableFolderUpdates() {
      onChanged();;
      if (folderUpdates_ == null) {
        folderUpdates_ = com.google.protobuf.MapField.newMapField(
            FolderUpdatesDefaultEntryHolder.defaultEntry);
      }
      if (!folderUpdates_.isMutable()) {
        folderUpdates_ = folderUpdates_.copy();
      }
      return folderUpdates_;
    }

    public int getFolderUpdatesCount() {
      return internalGetFolderUpdates().getMap().size();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public boolean containsFolderUpdates(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFolderUpdates().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFolderUpdatesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdates() {
      return getFolderUpdatesMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdatesMap() {
      return internalGetFolderUpdates().getMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
        java.lang.String key,
        net.anysync.protoc.ServerFolderUpdates defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
          internalGetFolderUpdates().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
          internalGetFolderUpdates().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFolderUpdates() {
      internalGetMutableFolderUpdates().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public Builder removeFolderUpdates(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFolderUpdates().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    getMutableFolderUpdates() {
      return internalGetMutableFolderUpdates().getMutableMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */
    public Builder putFolderUpdates(
        java.lang.String key,
        net.anysync.protoc.ServerFolderUpdates value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFolderUpdates().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
     */

    public Builder putAllFolderUpdates(
        java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> values) {
      internalGetMutableFolderUpdates().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, net.anysync.protoc.ModifiedFolder> serverChanges_;
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ModifiedFolder>
    internalGetServerChanges() {
      if (serverChanges_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ServerChangesDefaultEntryHolder.defaultEntry);
      }
      return serverChanges_;
    }
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ModifiedFolder>
    internalGetMutableServerChanges() {
      onChanged();;
      if (serverChanges_ == null) {
        serverChanges_ = com.google.protobuf.MapField.newMapField(
            ServerChangesDefaultEntryHolder.defaultEntry);
      }
      if (!serverChanges_.isMutable()) {
        serverChanges_ = serverChanges_.copy();
      }
      return serverChanges_;
    }

    public int getServerChangesCount() {
      return internalGetServerChanges().getMap().size();
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public boolean containsServerChanges(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetServerChanges().getMap().containsKey(key);
    }
    /**
     * Use {@link #getServerChangesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> getServerChanges() {
      return getServerChangesMap();
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> getServerChangesMap() {
      return internalGetServerChanges().getMap();
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public net.anysync.protoc.ModifiedFolder getServerChangesOrDefault(
        java.lang.String key,
        net.anysync.protoc.ModifiedFolder defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> map =
          internalGetServerChanges().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public net.anysync.protoc.ModifiedFolder getServerChangesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> map =
          internalGetServerChanges().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearServerChanges() {
      internalGetMutableServerChanges().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public Builder removeServerChanges(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableServerChanges().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder>
    getMutableServerChanges() {
      return internalGetMutableServerChanges().getMutableMap();
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */
    public Builder putServerChanges(
        java.lang.String key,
        net.anysync.protoc.ModifiedFolder value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableServerChanges().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
     */

    public Builder putAllServerChanges(
        java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder> values) {
      internalGetMutableServerChanges().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.BinLogResponse)
  }

  // @@protoc_insertion_point(class_scope:utils.BinLogResponse)
  private static final net.anysync.protoc.BinLogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.BinLogResponse();
  }

  public static net.anysync.protoc.BinLogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinLogResponse>
      PARSER = new com.google.protobuf.AbstractParser<BinLogResponse>() {
    public BinLogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BinLogResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BinLogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinLogResponse> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.BinLogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

