// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface BinLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.BinLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */
  int getFolderUpdatesCount();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */
  boolean containsFolderUpdates(
      java.lang.String key);
  /**
   * Use {@link #getFolderUpdatesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdates();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdatesMap();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ServerFolderUpdates defaultValue);
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 1;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */
  int getServerChangesCount();
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */
  boolean containsServerChanges(
      java.lang.String key);
  /**
   * Use {@link #getServerChangesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder>
  getServerChanges();
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */
  java.util.Map<java.lang.String, net.anysync.protoc.ModifiedFolder>
  getServerChangesMap();
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  net.anysync.protoc.ModifiedFolder getServerChangesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ModifiedFolder defaultValue);
  /**
   * <code>map&lt;string, .utils.ModifiedFolder&gt; ServerChanges = 2;</code>
   */

  net.anysync.protoc.ModifiedFolder getServerChangesOrThrow(
      java.lang.String key);
}
