// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface FileAttribsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.FileAttribs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, bytes&gt; Attribs = 1;</code>
   */
  int getAttribsCount();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 1;</code>
   */
  boolean containsAttribs(
      java.lang.String key);
  /**
   * Use {@link #getAttribsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getAttribs();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getAttribsMap();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 1;</code>
   */

  com.google.protobuf.ByteString getAttribsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 1;</code>
   */

  com.google.protobuf.ByteString getAttribsOrThrow(
      java.lang.String key);
}
