// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface ModifiedFolderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.ModifiedFolder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string FolderHash = 1;</code>
   */
  java.lang.String getFolderHash();
  /**
   * <code>string FolderHash = 1;</code>
   */
  com.google.protobuf.ByteString
      getFolderHashBytes();

  /**
   * <code>string RelativePath = 2;</code>
   */
  java.lang.String getRelativePath();
  /**
   * <code>string RelativePath = 2;</code>
   */
  com.google.protobuf.ByteString
      getRelativePathBytes();

  /**
   * <code>string ParentHash = 3;</code>
   */
  java.lang.String getParentHash();
  /**
   * <code>string ParentHash = 3;</code>
   */
  com.google.protobuf.ByteString
      getParentHashBytes();

  /**
   * <code>map&lt;uint32, .utils.ModifiedRow&gt; Rows = 4;</code>
   */
  int getRowsCount();
  /**
   * <code>map&lt;uint32, .utils.ModifiedRow&gt; Rows = 4;</code>
   */
  boolean containsRows(
      int key);
  /**
   * Use {@link #getRowsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, net.anysync.protoc.ModifiedRow>
  getRows();
  /**
   * <code>map&lt;uint32, .utils.ModifiedRow&gt; Rows = 4;</code>
   */
  java.util.Map<java.lang.Integer, net.anysync.protoc.ModifiedRow>
  getRowsMap();
  /**
   * <code>map&lt;uint32, .utils.ModifiedRow&gt; Rows = 4;</code>
   */

  net.anysync.protoc.ModifiedRow getRowsOrDefault(
      int key,
      net.anysync.protoc.ModifiedRow defaultValue);
  /**
   * <code>map&lt;uint32, .utils.ModifiedRow&gt; Rows = 4;</code>
   */

  net.anysync.protoc.ModifiedRow getRowsOrThrow(
      int key);

  /**
   * <code>uint32 Offset = 5;</code>
   */
  int getOffset();

  /**
   * <code>uint32 End = 6;</code>
   */
  int getEnd();

  /**
   * <code>string RepoHash = 7;</code>
   */
  java.lang.String getRepoHash();
  /**
   * <code>string RepoHash = 7;</code>
   */
  com.google.protobuf.ByteString
      getRepoHashBytes();

  /**
   * <code>bool HasThumbnail = 8;</code>
   */
  boolean getHasThumbnail();
}
