// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.ModifiedData}
 */
public  final class ModifiedData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.ModifiedData)
    ModifiedDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModifiedData.newBuilder() to construct.
  private ModifiedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModifiedData() {
    version_ = "";
    server_ = "";
    user_ = "";
    auth_ = "";
    token_ = "";
    deviceID_ = 0;
    time_ = 0;
    notify_ = false;
    folders_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModifiedData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            server_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            user_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            auth_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 48: {

            deviceID_ = input.readUInt32();
            break;
          }
          case 56: {

            time_ = input.readUInt32();
            break;
          }
          case 64: {

            notify_ = input.readBool();
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              headers_ = com.google.protobuf.MapField.newMapField(
                  HeadersDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000100;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            headers__ = input.readMessage(
                HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            headers_.getMutableMap().put(
                headers__.getKey(), headers__.getValue());
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              folders_ = new java.util.ArrayList<net.anysync.protoc.ModifiedFolder>();
              mutable_bitField0_ |= 0x00000200;
            }
            folders_.add(
                input.readMessage(net.anysync.protoc.ModifiedFolder.parser(), extensionRegistry));
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              objects_ = com.google.protobuf.MapField.newMapField(
                  ObjectsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000400;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            objects__ = input.readMessage(
                ObjectsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            objects_.getMutableMap().put(
                objects__.getKey(), objects__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        folders_ = java.util.Collections.unmodifiableList(folders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 9:
        return internalGetHeaders();
      case 11:
        return internalGetObjects();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.ModifiedData.class, net.anysync.protoc.ModifiedData.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object version_;
  /**
   * <code>string Version = 1;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string Version = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_FIELD_NUMBER = 2;
  private volatile java.lang.Object server_;
  /**
   * <code>string Server = 2;</code>
   */
  public java.lang.String getServer() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      server_ = s;
      return s;
    }
  }
  /**
   * <code>string Server = 2;</code>
   */
  public com.google.protobuf.ByteString
      getServerBytes() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      server_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIELD_NUMBER = 3;
  private volatile java.lang.Object user_;
  /**
   * <code>string User = 3;</code>
   */
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string User = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTH_FIELD_NUMBER = 4;
  private volatile java.lang.Object auth_;
  /**
   * <code>string Auth = 4;</code>
   */
  public java.lang.String getAuth() {
    java.lang.Object ref = auth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      auth_ = s;
      return s;
    }
  }
  /**
   * <code>string Auth = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAuthBytes() {
    java.lang.Object ref = auth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      auth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 5;
  private volatile java.lang.Object token_;
  /**
   * <code>string Token = 5;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string Token = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 6;
  private int deviceID_;
  /**
   * <code>uint32 DeviceID = 6;</code>
   */
  public int getDeviceID() {
    return deviceID_;
  }

  public static final int TIME_FIELD_NUMBER = 7;
  private int time_;
  /**
   * <code>uint32 Time = 7;</code>
   */
  public int getTime() {
    return time_;
  }

  public static final int NOTIFY_FIELD_NUMBER = 8;
  private boolean notify_;
  /**
   * <code>bool Notify = 8;</code>
   */
  public boolean getNotify() {
    return notify_;
  }

  public static final int HEADERS_FIELD_NUMBER = 9;
  private static final class HeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_HeadersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> headers_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetHeaders() {
    if (headers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HeadersDefaultEntryHolder.defaultEntry);
    }
    return headers_;
  }

  public int getHeadersCount() {
    return internalGetHeaders().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; Headers = 9;</code>
   */

  public boolean containsHeaders(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetHeaders().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
    return getHeadersMap();
  }
  /**
   * <code>map&lt;string, string&gt; Headers = 9;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
    return internalGetHeaders().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; Headers = 9;</code>
   */

  public java.lang.String getHeadersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; Headers = 9;</code>
   */

  public java.lang.String getHeadersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int FOLDERS_FIELD_NUMBER = 10;
  private java.util.List<net.anysync.protoc.ModifiedFolder> folders_;
  /**
   * <pre>
   *Must use list instead of map to preserve order
   * </pre>
   *
   * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
   */
  public java.util.List<net.anysync.protoc.ModifiedFolder> getFoldersList() {
    return folders_;
  }
  /**
   * <pre>
   *Must use list instead of map to preserve order
   * </pre>
   *
   * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
   */
  public java.util.List<? extends net.anysync.protoc.ModifiedFolderOrBuilder> 
      getFoldersOrBuilderList() {
    return folders_;
  }
  /**
   * <pre>
   *Must use list instead of map to preserve order
   * </pre>
   *
   * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
   */
  public int getFoldersCount() {
    return folders_.size();
  }
  /**
   * <pre>
   *Must use list instead of map to preserve order
   * </pre>
   *
   * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
   */
  public net.anysync.protoc.ModifiedFolder getFolders(int index) {
    return folders_.get(index);
  }
  /**
   * <pre>
   *Must use list instead of map to preserve order
   * </pre>
   *
   * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
   */
  public net.anysync.protoc.ModifiedFolderOrBuilder getFoldersOrBuilder(
      int index) {
    return folders_.get(index);
  }

  public static final int OBJECTS_FIELD_NUMBER = 11;
  private static final class ObjectsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_ObjectsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> objects_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetObjects() {
    if (objects_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ObjectsDefaultEntryHolder.defaultEntry);
    }
    return objects_;
  }

  public int getObjectsCount() {
    return internalGetObjects().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 11;</code>
   */

  public boolean containsObjects(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetObjects().getMap().containsKey(key);
  }
  /**
   * Use {@link #getObjectsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjects() {
    return getObjectsMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 11;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjectsMap() {
    return internalGetObjects().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 11;</code>
   */

  public com.google.protobuf.ByteString getObjectsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetObjects().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 11;</code>
   */

  public com.google.protobuf.ByteString getObjectsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetObjects().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (!getServerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, server_);
    }
    if (!getUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, user_);
    }
    if (!getAuthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, auth_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
    }
    if (deviceID_ != 0) {
      output.writeUInt32(6, deviceID_);
    }
    if (time_ != 0) {
      output.writeUInt32(7, time_);
    }
    if (notify_ != false) {
      output.writeBool(8, notify_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetHeaders(),
        HeadersDefaultEntryHolder.defaultEntry,
        9);
    for (int i = 0; i < folders_.size(); i++) {
      output.writeMessage(10, folders_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetObjects(),
        ObjectsDefaultEntryHolder.defaultEntry,
        11);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (!getServerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, server_);
    }
    if (!getUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, user_);
    }
    if (!getAuthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, auth_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
    }
    if (deviceID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, deviceID_);
    }
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, time_);
    }
    if (notify_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, notify_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, headers__);
    }
    for (int i = 0; i < folders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, folders_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetObjects().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      objects__ = ObjectsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, objects__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.ModifiedData)) {
      return super.equals(obj);
    }
    net.anysync.protoc.ModifiedData other = (net.anysync.protoc.ModifiedData) obj;

    boolean result = true;
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && getServer()
        .equals(other.getServer());
    result = result && getUser()
        .equals(other.getUser());
    result = result && getAuth()
        .equals(other.getAuth());
    result = result && getToken()
        .equals(other.getToken());
    result = result && (getDeviceID()
        == other.getDeviceID());
    result = result && (getTime()
        == other.getTime());
    result = result && (getNotify()
        == other.getNotify());
    result = result && internalGetHeaders().equals(
        other.internalGetHeaders());
    result = result && getFoldersList()
        .equals(other.getFoldersList());
    result = result && internalGetObjects().equals(
        other.internalGetObjects());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + SERVER_FIELD_NUMBER;
    hash = (53 * hash) + getServer().hashCode();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    hash = (37 * hash) + AUTH_FIELD_NUMBER;
    hash = (53 * hash) + getAuth().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceID();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (37 * hash) + NOTIFY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNotify());
    if (!internalGetHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeaders().hashCode();
    }
    if (getFoldersCount() > 0) {
      hash = (37 * hash) + FOLDERS_FIELD_NUMBER;
      hash = (53 * hash) + getFoldersList().hashCode();
    }
    if (!internalGetObjects().getMap().isEmpty()) {
      hash = (37 * hash) + OBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetObjects().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.ModifiedData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ModifiedData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ModifiedData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ModifiedData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.ModifiedData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.ModifiedData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.ModifiedData)
      net.anysync.protoc.ModifiedDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetHeaders();
        case 11:
          return internalGetObjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetMutableHeaders();
        case 11:
          return internalGetMutableObjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.ModifiedData.class, net.anysync.protoc.ModifiedData.Builder.class);
    }

    // Construct using net.anysync.protoc.ModifiedData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFoldersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      version_ = "";

      server_ = "";

      user_ = "";

      auth_ = "";

      token_ = "";

      deviceID_ = 0;

      time_ = 0;

      notify_ = false;

      internalGetMutableHeaders().clear();
      if (foldersBuilder_ == null) {
        folders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        foldersBuilder_.clear();
      }
      internalGetMutableObjects().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ModifiedData_descriptor;
    }

    public net.anysync.protoc.ModifiedData getDefaultInstanceForType() {
      return net.anysync.protoc.ModifiedData.getDefaultInstance();
    }

    public net.anysync.protoc.ModifiedData build() {
      net.anysync.protoc.ModifiedData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.ModifiedData buildPartial() {
      net.anysync.protoc.ModifiedData result = new net.anysync.protoc.ModifiedData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.version_ = version_;
      result.server_ = server_;
      result.user_ = user_;
      result.auth_ = auth_;
      result.token_ = token_;
      result.deviceID_ = deviceID_;
      result.time_ = time_;
      result.notify_ = notify_;
      result.headers_ = internalGetHeaders();
      result.headers_.makeImmutable();
      if (foldersBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          folders_ = java.util.Collections.unmodifiableList(folders_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.folders_ = folders_;
      } else {
        result.folders_ = foldersBuilder_.build();
      }
      result.objects_ = internalGetObjects();
      result.objects_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.ModifiedData) {
        return mergeFrom((net.anysync.protoc.ModifiedData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.ModifiedData other) {
      if (other == net.anysync.protoc.ModifiedData.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (!other.getServer().isEmpty()) {
        server_ = other.server_;
        onChanged();
      }
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      if (!other.getAuth().isEmpty()) {
        auth_ = other.auth_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (other.getDeviceID() != 0) {
        setDeviceID(other.getDeviceID());
      }
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (other.getNotify() != false) {
        setNotify(other.getNotify());
      }
      internalGetMutableHeaders().mergeFrom(
          other.internalGetHeaders());
      if (foldersBuilder_ == null) {
        if (!other.folders_.isEmpty()) {
          if (folders_.isEmpty()) {
            folders_ = other.folders_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureFoldersIsMutable();
            folders_.addAll(other.folders_);
          }
          onChanged();
        }
      } else {
        if (!other.folders_.isEmpty()) {
          if (foldersBuilder_.isEmpty()) {
            foldersBuilder_.dispose();
            foldersBuilder_ = null;
            folders_ = other.folders_;
            bitField0_ = (bitField0_ & ~0x00000200);
            foldersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFoldersFieldBuilder() : null;
          } else {
            foldersBuilder_.addAllMessages(other.folders_);
          }
        }
      }
      internalGetMutableObjects().mergeFrom(
          other.internalGetObjects());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.ModifiedData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.ModifiedData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object version_ = "";
    /**
     * <code>string Version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Version = 1;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string Version = 1;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object server_ = "";
    /**
     * <code>string Server = 2;</code>
     */
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        server_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Server = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Server = 2;</code>
     */
    public Builder setServer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      server_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Server = 2;</code>
     */
    public Builder clearServer() {
      
      server_ = getDefaultInstance().getServer();
      onChanged();
      return this;
    }
    /**
     * <code>string Server = 2;</code>
     */
    public Builder setServerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      server_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object user_ = "";
    /**
     * <code>string User = 3;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string User = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string User = 3;</code>
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string User = 3;</code>
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string User = 3;</code>
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object auth_ = "";
    /**
     * <code>string Auth = 4;</code>
     */
    public java.lang.String getAuth() {
      java.lang.Object ref = auth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        auth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Auth = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAuthBytes() {
      java.lang.Object ref = auth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Auth = 4;</code>
     */
    public Builder setAuth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      auth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Auth = 4;</code>
     */
    public Builder clearAuth() {
      
      auth_ = getDefaultInstance().getAuth();
      onChanged();
      return this;
    }
    /**
     * <code>string Auth = 4;</code>
     */
    public Builder setAuthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      auth_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>string Token = 5;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Token = 5;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Token = 5;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>string Token = 5;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private int deviceID_ ;
    /**
     * <code>uint32 DeviceID = 6;</code>
     */
    public int getDeviceID() {
      return deviceID_;
    }
    /**
     * <code>uint32 DeviceID = 6;</code>
     */
    public Builder setDeviceID(int value) {
      
      deviceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 DeviceID = 6;</code>
     */
    public Builder clearDeviceID() {
      
      deviceID_ = 0;
      onChanged();
      return this;
    }

    private int time_ ;
    /**
     * <code>uint32 Time = 7;</code>
     */
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 Time = 7;</code>
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Time = 7;</code>
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private boolean notify_ ;
    /**
     * <code>bool Notify = 8;</code>
     */
    public boolean getNotify() {
      return notify_;
    }
    /**
     * <code>bool Notify = 8;</code>
     */
    public Builder setNotify(boolean value) {
      
      notify_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool Notify = 8;</code>
     */
    public Builder clearNotify() {
      
      notify_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableHeaders() {
      onChanged();;
      if (headers_ == null) {
        headers_ = com.google.protobuf.MapField.newMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      if (!headers_.isMutable()) {
        headers_ = headers_.copy();
      }
      return headers_;
    }

    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public boolean containsHeaders(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHeaders() {
      internalGetMutableHeaders().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public Builder removeHeaders(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableHeaders().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableHeaders() {
      return internalGetMutableHeaders().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */
    public Builder putHeaders(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableHeaders().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Headers = 9;</code>
     */

    public Builder putAllHeaders(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableHeaders().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<net.anysync.protoc.ModifiedFolder> folders_ =
      java.util.Collections.emptyList();
    private void ensureFoldersIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        folders_ = new java.util.ArrayList<net.anysync.protoc.ModifiedFolder>(folders_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.ModifiedFolder, net.anysync.protoc.ModifiedFolder.Builder, net.anysync.protoc.ModifiedFolderOrBuilder> foldersBuilder_;

    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public java.util.List<net.anysync.protoc.ModifiedFolder> getFoldersList() {
      if (foldersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(folders_);
      } else {
        return foldersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public int getFoldersCount() {
      if (foldersBuilder_ == null) {
        return folders_.size();
      } else {
        return foldersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public net.anysync.protoc.ModifiedFolder getFolders(int index) {
      if (foldersBuilder_ == null) {
        return folders_.get(index);
      } else {
        return foldersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder setFolders(
        int index, net.anysync.protoc.ModifiedFolder value) {
      if (foldersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoldersIsMutable();
        folders_.set(index, value);
        onChanged();
      } else {
        foldersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder setFolders(
        int index, net.anysync.protoc.ModifiedFolder.Builder builderForValue) {
      if (foldersBuilder_ == null) {
        ensureFoldersIsMutable();
        folders_.set(index, builderForValue.build());
        onChanged();
      } else {
        foldersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder addFolders(net.anysync.protoc.ModifiedFolder value) {
      if (foldersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoldersIsMutable();
        folders_.add(value);
        onChanged();
      } else {
        foldersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder addFolders(
        int index, net.anysync.protoc.ModifiedFolder value) {
      if (foldersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFoldersIsMutable();
        folders_.add(index, value);
        onChanged();
      } else {
        foldersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder addFolders(
        net.anysync.protoc.ModifiedFolder.Builder builderForValue) {
      if (foldersBuilder_ == null) {
        ensureFoldersIsMutable();
        folders_.add(builderForValue.build());
        onChanged();
      } else {
        foldersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder addFolders(
        int index, net.anysync.protoc.ModifiedFolder.Builder builderForValue) {
      if (foldersBuilder_ == null) {
        ensureFoldersIsMutable();
        folders_.add(index, builderForValue.build());
        onChanged();
      } else {
        foldersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder addAllFolders(
        java.lang.Iterable<? extends net.anysync.protoc.ModifiedFolder> values) {
      if (foldersBuilder_ == null) {
        ensureFoldersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, folders_);
        onChanged();
      } else {
        foldersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder clearFolders() {
      if (foldersBuilder_ == null) {
        folders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        foldersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public Builder removeFolders(int index) {
      if (foldersBuilder_ == null) {
        ensureFoldersIsMutable();
        folders_.remove(index);
        onChanged();
      } else {
        foldersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public net.anysync.protoc.ModifiedFolder.Builder getFoldersBuilder(
        int index) {
      return getFoldersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public net.anysync.protoc.ModifiedFolderOrBuilder getFoldersOrBuilder(
        int index) {
      if (foldersBuilder_ == null) {
        return folders_.get(index);  } else {
        return foldersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public java.util.List<? extends net.anysync.protoc.ModifiedFolderOrBuilder> 
         getFoldersOrBuilderList() {
      if (foldersBuilder_ != null) {
        return foldersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(folders_);
      }
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public net.anysync.protoc.ModifiedFolder.Builder addFoldersBuilder() {
      return getFoldersFieldBuilder().addBuilder(
          net.anysync.protoc.ModifiedFolder.getDefaultInstance());
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public net.anysync.protoc.ModifiedFolder.Builder addFoldersBuilder(
        int index) {
      return getFoldersFieldBuilder().addBuilder(
          index, net.anysync.protoc.ModifiedFolder.getDefaultInstance());
    }
    /**
     * <pre>
     *Must use list instead of map to preserve order
     * </pre>
     *
     * <code>repeated .utils.ModifiedFolder Folders = 10;</code>
     */
    public java.util.List<net.anysync.protoc.ModifiedFolder.Builder> 
         getFoldersBuilderList() {
      return getFoldersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.ModifiedFolder, net.anysync.protoc.ModifiedFolder.Builder, net.anysync.protoc.ModifiedFolderOrBuilder> 
        getFoldersFieldBuilder() {
      if (foldersBuilder_ == null) {
        foldersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.anysync.protoc.ModifiedFolder, net.anysync.protoc.ModifiedFolder.Builder, net.anysync.protoc.ModifiedFolderOrBuilder>(
                folders_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        folders_ = null;
      }
      return foldersBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> objects_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetObjects() {
      if (objects_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ObjectsDefaultEntryHolder.defaultEntry);
      }
      return objects_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableObjects() {
      onChanged();;
      if (objects_ == null) {
        objects_ = com.google.protobuf.MapField.newMapField(
            ObjectsDefaultEntryHolder.defaultEntry);
      }
      if (!objects_.isMutable()) {
        objects_ = objects_.copy();
      }
      return objects_;
    }

    public int getObjectsCount() {
      return internalGetObjects().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public boolean containsObjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetObjects().getMap().containsKey(key);
    }
    /**
     * Use {@link #getObjectsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjects() {
      return getObjectsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjectsMap() {
      return internalGetObjects().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public com.google.protobuf.ByteString getObjectsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetObjects().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public com.google.protobuf.ByteString getObjectsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetObjects().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearObjects() {
      internalGetMutableObjects().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public Builder removeObjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableObjects().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableObjects() {
      return internalGetMutableObjects().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */
    public Builder putObjects(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableObjects().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 11;</code>
     */

    public Builder putAllObjects(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableObjects().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.ModifiedData)
  }

  // @@protoc_insertion_point(class_scope:utils.ModifiedData)
  private static final net.anysync.protoc.ModifiedData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.ModifiedData();
  }

  public static net.anysync.protoc.ModifiedData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModifiedData>
      PARSER = new com.google.protobuf.AbstractParser<ModifiedData>() {
    public ModifiedData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModifiedData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModifiedData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModifiedData> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.ModifiedData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

