// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public final class ProtoBufData {
  private ProtoBufData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UserRequest_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UserRequest_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UserRequest_Data2Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UserRequest_Data2Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UserRequest_Data3Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UserRequest_Data3Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UserAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UserAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ActionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ActionResponse_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ActionResponse_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ActionResponse_Data2Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ActionResponse_Data2Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ActionResponse_Data3Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ActionResponse_Data3Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedRow_AttribsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedRow_AttribsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedFolder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedFolder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedFolder_RowsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedFolder_RowsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedData_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedData_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ModifiedData_ObjectsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ModifiedData_ObjectsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_WriteTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_WriteTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_WriteTask_AttribsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_WriteTask_AttribsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ServerFolderUpdates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ServerFolderUpdates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_BinLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_BinLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_BinLogResponse_FolderUpdatesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_BinLogResponse_FolderUpdatesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_BinLogResponse_ServerChangesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_BinLogResponse_ServerChangesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ServerSyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ServerSyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ServerSyncResponse_PropsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ServerSyncResponse_PropsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ServerSyncResponse_ObjectsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ServerSyncResponse_ObjectsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_FileAttribs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_FileAttribs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_FileAttribs_AttribsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_FileAttribs_AttribsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_RemoteObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_RemoteObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_RemoteObject_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_RemoteObject_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_Repository_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_Repository_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ShareFolder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ShareFolder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_ShareFolder_MemberKeysEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_ShareFolder_MemberKeysEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UpdateDatTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UpdateDatTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UpdateDatTask_FolderUpdatesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UpdateDatTask_FolderUpdatesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UpdateDatTask_ObjectsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UpdateDatTask_ObjectsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utils_UploadStagingTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utils_UploadStagingTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rescan.proto\022\005utils\"\275\003\n\013UserRequest\022\017\n" +
      "\007Version\030\001 \001(\t\022\016\n\006Server\030\002 \001(\t\022\016\n\006UserID" +
      "\030\003 \001(\t\022\r\n\005Email\030\004 \001(\t\022\014\n\004Auth\030\005 \001(\t\022\020\n\010D" +
      "eviceID\030\006 \001(\r\022\014\n\004Time\030\007 \001(\r\022\016\n\006Action\030\010 " +
      "\001(\t\022*\n\004Data\030\t \003(\0132\034.utils.UserRequest.Da" +
      "taEntry\022,\n\005Data2\030\n \003(\0132\035.utils.UserReque" +
      "st.Data2Entry\022,\n\005Data3\030\013 \003(\0132\035.utils.Use" +
      "rRequest.Data3Entry\022\037\n\005Tasks\030\014 \003(\0132\020.uti" +
      "ls.WriteTask\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\014:\0028\001\032,\n\nData2Entry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\032,\n\nData3Entry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\220\004\n\013UserAc" +
      "count\022\n\n\002ID\030\001 \001(\005\022\023\n\013AccountType\030\002 \001(\005\022\023" +
      "\n\013AccountRole\030\003 \001(\005\022\024\n\014Organization\030\004 \001(" +
      "\t\022\r\n\005Group\030\005 \001(\t\022\r\n\005Email\030\006 \001(\t\022\014\n\004Name\030" +
      "\007 \001(\t\022\023\n\013AccessToken\030\010 \001(\014\022\r\n\005MaxID\030\t \001(" +
      "\005\022\021\n\tLastLogin\030\n \001(\r\022\017\n\007AuthKey\030\013 \001(\014\022\016\n" +
      "\006Server\030\014 \001(\t\022\016\n\006PubKey\030\r \001(\014\022\023\n\013RealAut" +
      "hKey\030\016 \001(\014\022\020\n\010Register\030\017 \001(\r\022\r\n\005Quota\030\020 " +
      "\001(\r\022\r\n\005Phone\030\021 \001(\t\022\016\n\006Bucket\030\022 \001(\t\022\016\n\006Ex" +
      "piry\030\023 \001(\r\022\016\n\006Prefix\030\024 \001(\t\022\017\n\007OrderID\030\025 " +
      "\001(\t\022\022\n\nOrderEmail\030\026 \001(\t\022\021\n\tOrderName\030\027 \001" +
      "(\t\022\022\n\nOrderPhone\030\030 \001(\t\022\020\n\010OrderRef\030\031 \001(\t" +
      "\022\024\n\014OrderCompany\030\032 \001(\t\022\021\n\tOrderDate\030\033 \001(" +
      "\r\022\025\n\rOrderReferrer\030\034 \001(\t\022\016\n\006LastIP\030\035 \001(\t" +
      "\"\373\002\n\016ActionResponse\022\014\n\004Time\030\001 \001(\r\022\014\n\004Use" +
      "r\030\002 \001(\t\022\020\n\010DeviceID\030\003 \001(\r\022\021\n\tErrorCode\030\004" +
      " \001(\r\022\016\n\006Action\030\005 \001(\t\022-\n\004Data\030\006 \003(\0132\037.uti" +
      "ls.ActionResponse.DataEntry\022/\n\005Data2\030\007 \003" +
      "(\0132 .utils.ActionResponse.Data2Entry\022/\n\005" +
      "Data3\030\010 \003(\0132 .utils.ActionResponse.Data3" +
      "Entry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\014:\0028\001\032,\n\nData2Entry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\014:\0028\001\032,\n\nData3Entry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"5\n\006Result\022\r\n\005titl" +
      "e\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\017\n\007snippet\030\003 \001(\t\"\226\002" +
      "\n\013ModifiedRow\022\025\n\rOperationMode\030\001 \001(\005\022\013\n\003" +
      "Row\030\002 \001(\014\022\020\n\010FileName\030\003 \001(\t\022\020\n\010Conflict\030" +
      "\004 \001(\005\022\030\n\020SendBackToClient\030\005 \001(\010\022\025\n\rPrevi" +
      "ousIndex\030\006 \001(\r\022\035\n\025OldFolderHashAndIndex\030" +
      "\007 \001(\t\0220\n\007Attribs\030\010 \003(\0132\037.utils.ModifiedR" +
      "ow.AttribsEntry\022\r\n\005IsDir\030\t \001(\010\032.\n\014Attrib" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\203" +
      "\002\n\016ModifiedFolder\022\022\n\nFolderHash\030\001 \001(\t\022\024\n" +
      "\014RelativePath\030\002 \001(\t\022\022\n\nParentHash\030\003 \001(\t\022" +
      "-\n\004Rows\030\004 \003(\0132\037.utils.ModifiedFolder.Row" +
      "sEntry\022\016\n\006Offset\030\005 \001(\r\022\013\n\003End\030\006 \001(\r\022\020\n\010R" +
      "epoHash\030\007 \001(\t\022\024\n\014HasThumbnail\030\010 \001(\010\032?\n\tR" +
      "owsEntry\022\013\n\003key\030\001 \001(\r\022!\n\005value\030\002 \001(\0132\022.u" +
      "tils.ModifiedRow:\0028\001\"\370\002\n\014ModifiedData\022\017\n" +
      "\007Version\030\001 \001(\t\022\016\n\006Server\030\002 \001(\t\022\014\n\004User\030\003" +
      " \001(\t\022\014\n\004Auth\030\004 \001(\t\022\r\n\005Token\030\005 \001(\t\022\020\n\010Dev" +
      "iceID\030\006 \001(\r\022\014\n\004Time\030\007 \001(\r\022\016\n\006Notify\030\010 \001(" +
      "\010\0221\n\007Headers\030\t \003(\0132 .utils.ModifiedData." +
      "HeadersEntry\022&\n\007Folders\030\n \003(\0132\025.utils.Mo" +
      "difiedFolder\0221\n\007Objects\030\013 \003(\0132 .utils.Mo" +
      "difiedData.ObjectsEntry\032.\n\014HeadersEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032.\n\014Objec" +
      "tsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"" +
      "\363\001\n\tWriteTask\022\014\n\004Mode\030\001 \001(\r\022\022\n\nFolderHas" +
      "h\030\002 \001(\t\022\r\n\005Index\030\003 \001(\r\022\020\n\010FileHash\030\004 \001(\t" +
      "\022\014\n\004Data\030\005 \001(\t\022\014\n\004Side\030\006 \001(\005\022\r\n\005Bytes\030\007 " +
      "\001(\014\022.\n\007Attribs\030\010 \003(\0132\035.utils.WriteTask.A" +
      "ttribsEntry\022\014\n\004Time\030\t \001(\r\022\n\n\002ID\030\n \001(\005\032.\n" +
      "\014AttribsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\014:\0028\001\"]\n\023ServerFolderUpdates\022\022\n\nFolderHa" +
      "sh\030\001 \001(\t\022\020\n\010RepoHash\030\002 \001(\t\022 \n\004Logs\030\003 \003(\013" +
      "2\022.utils.ModifiedRow\"\261\002\n\016BinLogResponse\022" +
      "?\n\rFolderUpdates\030\001 \003(\0132(.utils.BinLogRes" +
      "ponse.FolderUpdatesEntry\022?\n\rServerChange" +
      "s\030\002 \003(\0132(.utils.BinLogResponse.ServerCha" +
      "ngesEntry\032P\n\022FolderUpdatesEntry\022\013\n\003key\030\001" +
      " \001(\t\022)\n\005value\030\002 \001(\0132\032.utils.ServerFolder" +
      "Updates:\0028\001\032K\n\022ServerChangesEntry\022\013\n\003key" +
      "\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.utils.ModifiedFo" +
      "lder:\0028\001\"\275\003\n\022ServerSyncResponse\0223\n\005Props" +
      "\030\001 \003(\0132$.utils.ServerSyncResponse.PropsE" +
      "ntry\022C\n\rFolderUpdates\030\002 \003(\0132,.utils.Serv" +
      "erSyncResponse.FolderUpdatesEntry\022\037\n\005Tas" +
      "ks\030\003 \003(\0132\020.utils.WriteTask\022\025\n\rTaskTopFol" +
      "der\030\004 \001(\t\0227\n\007Objects\030\005 \003(\0132&.utils.Serve" +
      "rSyncResponse.ObjectsEntry\022\014\n\004Code\030\006 \001(\005" +
      "\032,\n\nPropsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\032P\n\022FolderUpdatesEntry\022\013\n\003key\030\001 \001(" +
      "\t\022)\n\005value\030\002 \001(\0132\032.utils.ServerFolderUpd" +
      "ates:\0028\001\032.\n\014ObjectsEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\014:\0028\001\"o\n\013FileAttribs\0220\n\007Attri" +
      "bs\030\001 \003(\0132\037.utils.FileAttribs.AttribsEntr" +
      "y\032.\n\014AttribsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\014:\0028\001\"\301\001\n\014RemoteObject\022\014\n\004Name\030\001 \001(\t" +
      "\022\r\n\005Value\030\002 \001(\t\022\014\n\004Type\030\003 \001(\t\022\014\n\004Root\030\004 " +
      "\001(\t\022+\n\004Data\030\005 \003(\0132\035.utils.RemoteObject.D" +
      "ataEntry\022\016\n\006Bucket\030\006 \001(\t\022\016\n\006Prefix\030\007 \001(\t" +
      "\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\"\336\001\n\nRepository\022\014\n\004Name\030\001 \001(\t\022\r\n\005Lo" +
      "cal\030\002 \001(\t\022\014\n\004Hash\030\003 \001(\t\022\027\n\017EncryptionLev" +
      "el\030\004 \001(\r\022#\n\006Remote\030\005 \003(\0132\023.utils.RemoteO" +
      "bject\022\022\n\nShareState\030\006 \001(\005\022\020\n\010Includes\030\007 " +
      "\001(\t\022\r\n\005Index\030\010 \001(\r\022\r\n\005Owner\030\t \001(\t\022\017\n\007Sha" +
      "reID\030\n \001(\t\022\022\n\nHashSuffix\030\013 \001(\t\"\246\002\n\013Share" +
      "Folder\022\014\n\004Name\030\001 \001(\t\022\014\n\004Hash\030\002 \001(\t\022\020\n\010In" +
      "cludes\030\003 \001(\t\022\022\n\nFolderHash\030\004 \001(\t\022\r\n\005Owne" +
      "r\030\005 \001(\t\022\022\n\nHashSuffix\030\006 \001(\t\022\016\n\006Expiry\030\007 " +
      "\001(\r\022\022\n\nPermission\030\010 \001(\r\0226\n\nMemberKeys\030\t " +
      "\003(\0132\".utils.ShareFolder.MemberKeysEntry\022" +
      "\027\n\017EncryptionLevel\030\n \001(\r\022\n\n\002ID\030\013 \001(\t\0321\n\017" +
      "MemberKeysEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"\263\002\n\rUpdateDatTask\022\014\n\004Time\030\001 \001(\r\022" +
      ">\n\rFolderUpdates\030\002 \003(\0132\'.utils.UpdateDat" +
      "Task.FolderUpdatesEntry\0222\n\007Objects\030\003 \003(\013" +
      "2!.utils.UpdateDatTask.ObjectsEntry\022\n\n\002I" +
      "D\030\004 \001(\005\022\022\n\nShareState\030\005 \001(\005\032P\n\022FolderUpd" +
      "atesEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032." +
      "utils.ServerFolderUpdates:\0028\001\032.\n\014Objects" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"X\n" +
      "\021UploadStagingTask\022 \n\003Msg\030\001 \001(\0132\023.utils." +
      "ModifiedData\022\022\n\nShareState\030\002 \001(\005\022\r\n\005owne" +
      "r\030\003 \001(\t2E\n\nSendResult\0227\n\tGetResult\022\023.uti" +
      "ls.ModifiedData\032\023.utils.ModifiedData\"\0002\262" +
      "\003\n\nSyncResult\022A\n\rGetSyncResult\022\023.utils.M" +
      "odifiedData\032\031.utils.ServerSyncResponse\"\000" +
      "\0229\n\nCallAction\022\022.utils.UserRequest\032\025.uti" +
      "ls.ActionResponse\"\000\0227\n\010Register\022\022.utils." +
      "UserRequest\032\025.utils.ActionResponse\"\000\0224\n\005" +
      "Login\022\022.utils.UserRequest\032\025.utils.Action" +
      "Response\"\000\022B\n\023RetrieveAccessToken\022\022.util" +
      "s.UserRequest\032\025.utils.ActionResponse\"\000\022:" +
      "\n\tSubscribe\022\022.utils.UserRequest\032\025.utils." +
      "ActionResponse\"\0000\001\0227\n\010SendData\022\022.utils.U" +
      "serRequest\032\025.utils.ActionResponse\"\000B)\n\022n" +
      "et.anysync.protocB\014ProtoBufDataP\001\242\002\002RSb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_utils_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_utils_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UserRequest_descriptor,
        new java.lang.String[] { "Version", "Server", "UserID", "Email", "Auth", "DeviceID", "Time", "Action", "Data", "Data2", "Data3", "Tasks", });
    internal_static_utils_UserRequest_DataEntry_descriptor =
      internal_static_utils_UserRequest_descriptor.getNestedTypes().get(0);
    internal_static_utils_UserRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UserRequest_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UserRequest_Data2Entry_descriptor =
      internal_static_utils_UserRequest_descriptor.getNestedTypes().get(1);
    internal_static_utils_UserRequest_Data2Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UserRequest_Data2Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UserRequest_Data3Entry_descriptor =
      internal_static_utils_UserRequest_descriptor.getNestedTypes().get(2);
    internal_static_utils_UserRequest_Data3Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UserRequest_Data3Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UserAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_utils_UserAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UserAccount_descriptor,
        new java.lang.String[] { "ID", "AccountType", "AccountRole", "Organization", "Group", "Email", "Name", "AccessToken", "MaxID", "LastLogin", "AuthKey", "Server", "PubKey", "RealAuthKey", "Register", "Quota", "Phone", "Bucket", "Expiry", "Prefix", "OrderID", "OrderEmail", "OrderName", "OrderPhone", "OrderRef", "OrderCompany", "OrderDate", "OrderReferrer", "LastIP", });
    internal_static_utils_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_utils_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ActionResponse_descriptor,
        new java.lang.String[] { "Time", "User", "DeviceID", "ErrorCode", "Action", "Data", "Data2", "Data3", });
    internal_static_utils_ActionResponse_DataEntry_descriptor =
      internal_static_utils_ActionResponse_descriptor.getNestedTypes().get(0);
    internal_static_utils_ActionResponse_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ActionResponse_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ActionResponse_Data2Entry_descriptor =
      internal_static_utils_ActionResponse_descriptor.getNestedTypes().get(1);
    internal_static_utils_ActionResponse_Data2Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ActionResponse_Data2Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ActionResponse_Data3Entry_descriptor =
      internal_static_utils_ActionResponse_descriptor.getNestedTypes().get(2);
    internal_static_utils_ActionResponse_Data3Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ActionResponse_Data3Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_Result_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_utils_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_Result_descriptor,
        new java.lang.String[] { "Title", "Url", "Snippet", });
    internal_static_utils_ModifiedRow_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_utils_ModifiedRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedRow_descriptor,
        new java.lang.String[] { "OperationMode", "Row", "FileName", "Conflict", "SendBackToClient", "PreviousIndex", "OldFolderHashAndIndex", "Attribs", "IsDir", });
    internal_static_utils_ModifiedRow_AttribsEntry_descriptor =
      internal_static_utils_ModifiedRow_descriptor.getNestedTypes().get(0);
    internal_static_utils_ModifiedRow_AttribsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedRow_AttribsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ModifiedFolder_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_utils_ModifiedFolder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedFolder_descriptor,
        new java.lang.String[] { "FolderHash", "RelativePath", "ParentHash", "Rows", "Offset", "End", "RepoHash", "HasThumbnail", });
    internal_static_utils_ModifiedFolder_RowsEntry_descriptor =
      internal_static_utils_ModifiedFolder_descriptor.getNestedTypes().get(0);
    internal_static_utils_ModifiedFolder_RowsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedFolder_RowsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ModifiedData_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_utils_ModifiedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedData_descriptor,
        new java.lang.String[] { "Version", "Server", "User", "Auth", "Token", "DeviceID", "Time", "Notify", "Headers", "Folders", "Objects", });
    internal_static_utils_ModifiedData_HeadersEntry_descriptor =
      internal_static_utils_ModifiedData_descriptor.getNestedTypes().get(0);
    internal_static_utils_ModifiedData_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedData_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ModifiedData_ObjectsEntry_descriptor =
      internal_static_utils_ModifiedData_descriptor.getNestedTypes().get(1);
    internal_static_utils_ModifiedData_ObjectsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ModifiedData_ObjectsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_WriteTask_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_utils_WriteTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_WriteTask_descriptor,
        new java.lang.String[] { "Mode", "FolderHash", "Index", "FileHash", "Data", "Side", "Bytes", "Attribs", "Time", "ID", });
    internal_static_utils_WriteTask_AttribsEntry_descriptor =
      internal_static_utils_WriteTask_descriptor.getNestedTypes().get(0);
    internal_static_utils_WriteTask_AttribsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_WriteTask_AttribsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ServerFolderUpdates_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_utils_ServerFolderUpdates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ServerFolderUpdates_descriptor,
        new java.lang.String[] { "FolderHash", "RepoHash", "Logs", });
    internal_static_utils_BinLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_utils_BinLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_BinLogResponse_descriptor,
        new java.lang.String[] { "FolderUpdates", "ServerChanges", });
    internal_static_utils_BinLogResponse_FolderUpdatesEntry_descriptor =
      internal_static_utils_BinLogResponse_descriptor.getNestedTypes().get(0);
    internal_static_utils_BinLogResponse_FolderUpdatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_BinLogResponse_FolderUpdatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_BinLogResponse_ServerChangesEntry_descriptor =
      internal_static_utils_BinLogResponse_descriptor.getNestedTypes().get(1);
    internal_static_utils_BinLogResponse_ServerChangesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_BinLogResponse_ServerChangesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ServerSyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_utils_ServerSyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ServerSyncResponse_descriptor,
        new java.lang.String[] { "Props", "FolderUpdates", "Tasks", "TaskTopFolder", "Objects", "Code", });
    internal_static_utils_ServerSyncResponse_PropsEntry_descriptor =
      internal_static_utils_ServerSyncResponse_descriptor.getNestedTypes().get(0);
    internal_static_utils_ServerSyncResponse_PropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ServerSyncResponse_PropsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_descriptor =
      internal_static_utils_ServerSyncResponse_descriptor.getNestedTypes().get(1);
    internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_ServerSyncResponse_ObjectsEntry_descriptor =
      internal_static_utils_ServerSyncResponse_descriptor.getNestedTypes().get(2);
    internal_static_utils_ServerSyncResponse_ObjectsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ServerSyncResponse_ObjectsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_FileAttribs_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_utils_FileAttribs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_FileAttribs_descriptor,
        new java.lang.String[] { "Attribs", });
    internal_static_utils_FileAttribs_AttribsEntry_descriptor =
      internal_static_utils_FileAttribs_descriptor.getNestedTypes().get(0);
    internal_static_utils_FileAttribs_AttribsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_FileAttribs_AttribsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_RemoteObject_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_utils_RemoteObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_RemoteObject_descriptor,
        new java.lang.String[] { "Name", "Value", "Type", "Root", "Data", "Bucket", "Prefix", });
    internal_static_utils_RemoteObject_DataEntry_descriptor =
      internal_static_utils_RemoteObject_descriptor.getNestedTypes().get(0);
    internal_static_utils_RemoteObject_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_RemoteObject_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_Repository_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_utils_Repository_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_Repository_descriptor,
        new java.lang.String[] { "Name", "Local", "Hash", "EncryptionLevel", "Remote", "ShareState", "Includes", "Index", "Owner", "ShareID", "HashSuffix", });
    internal_static_utils_ShareFolder_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_utils_ShareFolder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ShareFolder_descriptor,
        new java.lang.String[] { "Name", "Hash", "Includes", "FolderHash", "Owner", "HashSuffix", "Expiry", "Permission", "MemberKeys", "EncryptionLevel", "ID", });
    internal_static_utils_ShareFolder_MemberKeysEntry_descriptor =
      internal_static_utils_ShareFolder_descriptor.getNestedTypes().get(0);
    internal_static_utils_ShareFolder_MemberKeysEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_ShareFolder_MemberKeysEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UpdateDatTask_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_utils_UpdateDatTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UpdateDatTask_descriptor,
        new java.lang.String[] { "Time", "FolderUpdates", "Objects", "ID", "ShareState", });
    internal_static_utils_UpdateDatTask_FolderUpdatesEntry_descriptor =
      internal_static_utils_UpdateDatTask_descriptor.getNestedTypes().get(0);
    internal_static_utils_UpdateDatTask_FolderUpdatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UpdateDatTask_FolderUpdatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UpdateDatTask_ObjectsEntry_descriptor =
      internal_static_utils_UpdateDatTask_descriptor.getNestedTypes().get(1);
    internal_static_utils_UpdateDatTask_ObjectsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UpdateDatTask_ObjectsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_utils_UploadStagingTask_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_utils_UploadStagingTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utils_UploadStagingTask_descriptor,
        new java.lang.String[] { "Msg", "ShareState", "Owner", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
