// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface RemoteObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.RemoteObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string Value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string Type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string Type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string Root = 4;</code>
   */
  java.lang.String getRoot();
  /**
   * <code>string Root = 4;</code>
   */
  com.google.protobuf.ByteString
      getRootBytes();

  /**
   * <code>map&lt;string, string&gt; Data = 5;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, string&gt; Data = 5;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getData();
  /**
   * <code>map&lt;string, string&gt; Data = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDataMap();
  /**
   * <code>map&lt;string, string&gt; Data = 5;</code>
   */

  java.lang.String getDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; Data = 5;</code>
   */

  java.lang.String getDataOrThrow(
      java.lang.String key);

  /**
   * <code>string Bucket = 6;</code>
   */
  java.lang.String getBucket();
  /**
   * <code>string Bucket = 6;</code>
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>string Prefix = 7;</code>
   */
  java.lang.String getPrefix();
  /**
   * <code>string Prefix = 7;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();
}
