// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.Repository}
 */
public  final class Repository extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.Repository)
    RepositoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Repository.newBuilder() to construct.
  private Repository(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Repository() {
    name_ = "";
    local_ = "";
    hash_ = "";
    encryptionLevel_ = 0;
    remote_ = java.util.Collections.emptyList();
    shareState_ = 0;
    includes_ = "";
    index_ = 0;
    owner_ = "";
    shareID_ = "";
    hashSuffix_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Repository(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            local_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            hash_ = s;
            break;
          }
          case 32: {

            encryptionLevel_ = input.readUInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              remote_ = new java.util.ArrayList<net.anysync.protoc.RemoteObject>();
              mutable_bitField0_ |= 0x00000010;
            }
            remote_.add(
                input.readMessage(net.anysync.protoc.RemoteObject.parser(), extensionRegistry));
            break;
          }
          case 48: {

            shareState_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            includes_ = s;
            break;
          }
          case 64: {

            index_ = input.readUInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            owner_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            shareID_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            hashSuffix_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        remote_ = java.util.Collections.unmodifiableList(remote_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_Repository_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_Repository_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.Repository.class, net.anysync.protoc.Repository.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string Name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string Name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCAL_FIELD_NUMBER = 2;
  private volatile java.lang.Object local_;
  /**
   * <code>string Local = 2;</code>
   */
  public java.lang.String getLocal() {
    java.lang.Object ref = local_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      local_ = s;
      return s;
    }
  }
  /**
   * <code>string Local = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLocalBytes() {
    java.lang.Object ref = local_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      local_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASH_FIELD_NUMBER = 3;
  private volatile java.lang.Object hash_;
  /**
   * <code>string Hash = 3;</code>
   */
  public java.lang.String getHash() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hash_ = s;
      return s;
    }
  }
  /**
   * <code>string Hash = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHashBytes() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTIONLEVEL_FIELD_NUMBER = 4;
  private int encryptionLevel_;
  /**
   * <code>uint32 EncryptionLevel = 4;</code>
   */
  public int getEncryptionLevel() {
    return encryptionLevel_;
  }

  public static final int REMOTE_FIELD_NUMBER = 5;
  private java.util.List<net.anysync.protoc.RemoteObject> remote_;
  /**
   * <code>repeated .utils.RemoteObject Remote = 5;</code>
   */
  public java.util.List<net.anysync.protoc.RemoteObject> getRemoteList() {
    return remote_;
  }
  /**
   * <code>repeated .utils.RemoteObject Remote = 5;</code>
   */
  public java.util.List<? extends net.anysync.protoc.RemoteObjectOrBuilder> 
      getRemoteOrBuilderList() {
    return remote_;
  }
  /**
   * <code>repeated .utils.RemoteObject Remote = 5;</code>
   */
  public int getRemoteCount() {
    return remote_.size();
  }
  /**
   * <code>repeated .utils.RemoteObject Remote = 5;</code>
   */
  public net.anysync.protoc.RemoteObject getRemote(int index) {
    return remote_.get(index);
  }
  /**
   * <code>repeated .utils.RemoteObject Remote = 5;</code>
   */
  public net.anysync.protoc.RemoteObjectOrBuilder getRemoteOrBuilder(
      int index) {
    return remote_.get(index);
  }

  public static final int SHARESTATE_FIELD_NUMBER = 6;
  private int shareState_;
  /**
   * <code>int32 ShareState = 6;</code>
   */
  public int getShareState() {
    return shareState_;
  }

  public static final int INCLUDES_FIELD_NUMBER = 7;
  private volatile java.lang.Object includes_;
  /**
   * <code>string Includes = 7;</code>
   */
  public java.lang.String getIncludes() {
    java.lang.Object ref = includes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      includes_ = s;
      return s;
    }
  }
  /**
   * <code>string Includes = 7;</code>
   */
  public com.google.protobuf.ByteString
      getIncludesBytes() {
    java.lang.Object ref = includes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      includes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 8;
  private int index_;
  /**
   * <code>uint32 Index = 8;</code>
   */
  public int getIndex() {
    return index_;
  }

  public static final int OWNER_FIELD_NUMBER = 9;
  private volatile java.lang.Object owner_;
  /**
   * <code>string Owner = 9;</code>
   */
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <code>string Owner = 9;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHAREID_FIELD_NUMBER = 10;
  private volatile java.lang.Object shareID_;
  /**
   * <code>string ShareID = 10;</code>
   */
  public java.lang.String getShareID() {
    java.lang.Object ref = shareID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shareID_ = s;
      return s;
    }
  }
  /**
   * <code>string ShareID = 10;</code>
   */
  public com.google.protobuf.ByteString
      getShareIDBytes() {
    java.lang.Object ref = shareID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shareID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASHSUFFIX_FIELD_NUMBER = 11;
  private volatile java.lang.Object hashSuffix_;
  /**
   * <code>string HashSuffix = 11;</code>
   */
  public java.lang.String getHashSuffix() {
    java.lang.Object ref = hashSuffix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hashSuffix_ = s;
      return s;
    }
  }
  /**
   * <code>string HashSuffix = 11;</code>
   */
  public com.google.protobuf.ByteString
      getHashSuffixBytes() {
    java.lang.Object ref = hashSuffix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hashSuffix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getLocalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, local_);
    }
    if (!getHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hash_);
    }
    if (encryptionLevel_ != 0) {
      output.writeUInt32(4, encryptionLevel_);
    }
    for (int i = 0; i < remote_.size(); i++) {
      output.writeMessage(5, remote_.get(i));
    }
    if (shareState_ != 0) {
      output.writeInt32(6, shareState_);
    }
    if (!getIncludesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, includes_);
    }
    if (index_ != 0) {
      output.writeUInt32(8, index_);
    }
    if (!getOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, owner_);
    }
    if (!getShareIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, shareID_);
    }
    if (!getHashSuffixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, hashSuffix_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getLocalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, local_);
    }
    if (!getHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hash_);
    }
    if (encryptionLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, encryptionLevel_);
    }
    for (int i = 0; i < remote_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, remote_.get(i));
    }
    if (shareState_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, shareState_);
    }
    if (!getIncludesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, includes_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, index_);
    }
    if (!getOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, owner_);
    }
    if (!getShareIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, shareID_);
    }
    if (!getHashSuffixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, hashSuffix_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.Repository)) {
      return super.equals(obj);
    }
    net.anysync.protoc.Repository other = (net.anysync.protoc.Repository) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getLocal()
        .equals(other.getLocal());
    result = result && getHash()
        .equals(other.getHash());
    result = result && (getEncryptionLevel()
        == other.getEncryptionLevel());
    result = result && getRemoteList()
        .equals(other.getRemoteList());
    result = result && (getShareState()
        == other.getShareState());
    result = result && getIncludes()
        .equals(other.getIncludes());
    result = result && (getIndex()
        == other.getIndex());
    result = result && getOwner()
        .equals(other.getOwner());
    result = result && getShareID()
        .equals(other.getShareID());
    result = result && getHashSuffix()
        .equals(other.getHashSuffix());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LOCAL_FIELD_NUMBER;
    hash = (53 * hash) + getLocal().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + ENCRYPTIONLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptionLevel();
    if (getRemoteCount() > 0) {
      hash = (37 * hash) + REMOTE_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteList().hashCode();
    }
    hash = (37 * hash) + SHARESTATE_FIELD_NUMBER;
    hash = (53 * hash) + getShareState();
    hash = (37 * hash) + INCLUDES_FIELD_NUMBER;
    hash = (53 * hash) + getIncludes().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + SHAREID_FIELD_NUMBER;
    hash = (53 * hash) + getShareID().hashCode();
    hash = (37 * hash) + HASHSUFFIX_FIELD_NUMBER;
    hash = (53 * hash) + getHashSuffix().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.Repository parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.Repository parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.Repository parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.Repository parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.Repository parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.Repository parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.Repository parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.Repository parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.Repository parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.Repository parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.Repository parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.Repository parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.Repository prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.Repository}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.Repository)
      net.anysync.protoc.RepositoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_Repository_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_Repository_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.Repository.class, net.anysync.protoc.Repository.Builder.class);
    }

    // Construct using net.anysync.protoc.Repository.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRemoteFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      local_ = "";

      hash_ = "";

      encryptionLevel_ = 0;

      if (remoteBuilder_ == null) {
        remote_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        remoteBuilder_.clear();
      }
      shareState_ = 0;

      includes_ = "";

      index_ = 0;

      owner_ = "";

      shareID_ = "";

      hashSuffix_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_Repository_descriptor;
    }

    public net.anysync.protoc.Repository getDefaultInstanceForType() {
      return net.anysync.protoc.Repository.getDefaultInstance();
    }

    public net.anysync.protoc.Repository build() {
      net.anysync.protoc.Repository result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.Repository buildPartial() {
      net.anysync.protoc.Repository result = new net.anysync.protoc.Repository(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.local_ = local_;
      result.hash_ = hash_;
      result.encryptionLevel_ = encryptionLevel_;
      if (remoteBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          remote_ = java.util.Collections.unmodifiableList(remote_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.remote_ = remote_;
      } else {
        result.remote_ = remoteBuilder_.build();
      }
      result.shareState_ = shareState_;
      result.includes_ = includes_;
      result.index_ = index_;
      result.owner_ = owner_;
      result.shareID_ = shareID_;
      result.hashSuffix_ = hashSuffix_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.Repository) {
        return mergeFrom((net.anysync.protoc.Repository)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.Repository other) {
      if (other == net.anysync.protoc.Repository.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getLocal().isEmpty()) {
        local_ = other.local_;
        onChanged();
      }
      if (!other.getHash().isEmpty()) {
        hash_ = other.hash_;
        onChanged();
      }
      if (other.getEncryptionLevel() != 0) {
        setEncryptionLevel(other.getEncryptionLevel());
      }
      if (remoteBuilder_ == null) {
        if (!other.remote_.isEmpty()) {
          if (remote_.isEmpty()) {
            remote_ = other.remote_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRemoteIsMutable();
            remote_.addAll(other.remote_);
          }
          onChanged();
        }
      } else {
        if (!other.remote_.isEmpty()) {
          if (remoteBuilder_.isEmpty()) {
            remoteBuilder_.dispose();
            remoteBuilder_ = null;
            remote_ = other.remote_;
            bitField0_ = (bitField0_ & ~0x00000010);
            remoteBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRemoteFieldBuilder() : null;
          } else {
            remoteBuilder_.addAllMessages(other.remote_);
          }
        }
      }
      if (other.getShareState() != 0) {
        setShareState(other.getShareState());
      }
      if (!other.getIncludes().isEmpty()) {
        includes_ = other.includes_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        onChanged();
      }
      if (!other.getShareID().isEmpty()) {
        shareID_ = other.shareID_;
        onChanged();
      }
      if (!other.getHashSuffix().isEmpty()) {
        hashSuffix_ = other.hashSuffix_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.Repository parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.Repository) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string Name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object local_ = "";
    /**
     * <code>string Local = 2;</code>
     */
    public java.lang.String getLocal() {
      java.lang.Object ref = local_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        local_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Local = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocalBytes() {
      java.lang.Object ref = local_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        local_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Local = 2;</code>
     */
    public Builder setLocal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      local_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Local = 2;</code>
     */
    public Builder clearLocal() {
      
      local_ = getDefaultInstance().getLocal();
      onChanged();
      return this;
    }
    /**
     * <code>string Local = 2;</code>
     */
    public Builder setLocalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      local_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hash_ = "";
    /**
     * <code>string Hash = 3;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Hash = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Hash = 3;</code>
     */
    public Builder setHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Hash = 3;</code>
     */
    public Builder clearHash() {
      
      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }
    /**
     * <code>string Hash = 3;</code>
     */
    public Builder setHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hash_ = value;
      onChanged();
      return this;
    }

    private int encryptionLevel_ ;
    /**
     * <code>uint32 EncryptionLevel = 4;</code>
     */
    public int getEncryptionLevel() {
      return encryptionLevel_;
    }
    /**
     * <code>uint32 EncryptionLevel = 4;</code>
     */
    public Builder setEncryptionLevel(int value) {
      
      encryptionLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 EncryptionLevel = 4;</code>
     */
    public Builder clearEncryptionLevel() {
      
      encryptionLevel_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<net.anysync.protoc.RemoteObject> remote_ =
      java.util.Collections.emptyList();
    private void ensureRemoteIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        remote_ = new java.util.ArrayList<net.anysync.protoc.RemoteObject>(remote_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.RemoteObject, net.anysync.protoc.RemoteObject.Builder, net.anysync.protoc.RemoteObjectOrBuilder> remoteBuilder_;

    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public java.util.List<net.anysync.protoc.RemoteObject> getRemoteList() {
      if (remoteBuilder_ == null) {
        return java.util.Collections.unmodifiableList(remote_);
      } else {
        return remoteBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public int getRemoteCount() {
      if (remoteBuilder_ == null) {
        return remote_.size();
      } else {
        return remoteBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public net.anysync.protoc.RemoteObject getRemote(int index) {
      if (remoteBuilder_ == null) {
        return remote_.get(index);
      } else {
        return remoteBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder setRemote(
        int index, net.anysync.protoc.RemoteObject value) {
      if (remoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemoteIsMutable();
        remote_.set(index, value);
        onChanged();
      } else {
        remoteBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder setRemote(
        int index, net.anysync.protoc.RemoteObject.Builder builderForValue) {
      if (remoteBuilder_ == null) {
        ensureRemoteIsMutable();
        remote_.set(index, builderForValue.build());
        onChanged();
      } else {
        remoteBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder addRemote(net.anysync.protoc.RemoteObject value) {
      if (remoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemoteIsMutable();
        remote_.add(value);
        onChanged();
      } else {
        remoteBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder addRemote(
        int index, net.anysync.protoc.RemoteObject value) {
      if (remoteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRemoteIsMutable();
        remote_.add(index, value);
        onChanged();
      } else {
        remoteBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder addRemote(
        net.anysync.protoc.RemoteObject.Builder builderForValue) {
      if (remoteBuilder_ == null) {
        ensureRemoteIsMutable();
        remote_.add(builderForValue.build());
        onChanged();
      } else {
        remoteBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder addRemote(
        int index, net.anysync.protoc.RemoteObject.Builder builderForValue) {
      if (remoteBuilder_ == null) {
        ensureRemoteIsMutable();
        remote_.add(index, builderForValue.build());
        onChanged();
      } else {
        remoteBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder addAllRemote(
        java.lang.Iterable<? extends net.anysync.protoc.RemoteObject> values) {
      if (remoteBuilder_ == null) {
        ensureRemoteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, remote_);
        onChanged();
      } else {
        remoteBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder clearRemote() {
      if (remoteBuilder_ == null) {
        remote_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        remoteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public Builder removeRemote(int index) {
      if (remoteBuilder_ == null) {
        ensureRemoteIsMutable();
        remote_.remove(index);
        onChanged();
      } else {
        remoteBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public net.anysync.protoc.RemoteObject.Builder getRemoteBuilder(
        int index) {
      return getRemoteFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public net.anysync.protoc.RemoteObjectOrBuilder getRemoteOrBuilder(
        int index) {
      if (remoteBuilder_ == null) {
        return remote_.get(index);  } else {
        return remoteBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public java.util.List<? extends net.anysync.protoc.RemoteObjectOrBuilder> 
         getRemoteOrBuilderList() {
      if (remoteBuilder_ != null) {
        return remoteBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(remote_);
      }
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public net.anysync.protoc.RemoteObject.Builder addRemoteBuilder() {
      return getRemoteFieldBuilder().addBuilder(
          net.anysync.protoc.RemoteObject.getDefaultInstance());
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public net.anysync.protoc.RemoteObject.Builder addRemoteBuilder(
        int index) {
      return getRemoteFieldBuilder().addBuilder(
          index, net.anysync.protoc.RemoteObject.getDefaultInstance());
    }
    /**
     * <code>repeated .utils.RemoteObject Remote = 5;</code>
     */
    public java.util.List<net.anysync.protoc.RemoteObject.Builder> 
         getRemoteBuilderList() {
      return getRemoteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.RemoteObject, net.anysync.protoc.RemoteObject.Builder, net.anysync.protoc.RemoteObjectOrBuilder> 
        getRemoteFieldBuilder() {
      if (remoteBuilder_ == null) {
        remoteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.anysync.protoc.RemoteObject, net.anysync.protoc.RemoteObject.Builder, net.anysync.protoc.RemoteObjectOrBuilder>(
                remote_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        remote_ = null;
      }
      return remoteBuilder_;
    }

    private int shareState_ ;
    /**
     * <code>int32 ShareState = 6;</code>
     */
    public int getShareState() {
      return shareState_;
    }
    /**
     * <code>int32 ShareState = 6;</code>
     */
    public Builder setShareState(int value) {
      
      shareState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ShareState = 6;</code>
     */
    public Builder clearShareState() {
      
      shareState_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object includes_ = "";
    /**
     * <code>string Includes = 7;</code>
     */
    public java.lang.String getIncludes() {
      java.lang.Object ref = includes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        includes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Includes = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIncludesBytes() {
      java.lang.Object ref = includes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        includes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Includes = 7;</code>
     */
    public Builder setIncludes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      includes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Includes = 7;</code>
     */
    public Builder clearIncludes() {
      
      includes_ = getDefaultInstance().getIncludes();
      onChanged();
      return this;
    }
    /**
     * <code>string Includes = 7;</code>
     */
    public Builder setIncludesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      includes_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <code>uint32 Index = 8;</code>
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 Index = 8;</code>
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Index = 8;</code>
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object owner_ = "";
    /**
     * <code>string Owner = 9;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Owner = 9;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Owner = 9;</code>
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      owner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Owner = 9;</code>
     */
    public Builder clearOwner() {
      
      owner_ = getDefaultInstance().getOwner();
      onChanged();
      return this;
    }
    /**
     * <code>string Owner = 9;</code>
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      owner_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shareID_ = "";
    /**
     * <code>string ShareID = 10;</code>
     */
    public java.lang.String getShareID() {
      java.lang.Object ref = shareID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shareID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ShareID = 10;</code>
     */
    public com.google.protobuf.ByteString
        getShareIDBytes() {
      java.lang.Object ref = shareID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shareID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ShareID = 10;</code>
     */
    public Builder setShareID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shareID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ShareID = 10;</code>
     */
    public Builder clearShareID() {
      
      shareID_ = getDefaultInstance().getShareID();
      onChanged();
      return this;
    }
    /**
     * <code>string ShareID = 10;</code>
     */
    public Builder setShareIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shareID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hashSuffix_ = "";
    /**
     * <code>string HashSuffix = 11;</code>
     */
    public java.lang.String getHashSuffix() {
      java.lang.Object ref = hashSuffix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashSuffix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string HashSuffix = 11;</code>
     */
    public com.google.protobuf.ByteString
        getHashSuffixBytes() {
      java.lang.Object ref = hashSuffix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashSuffix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string HashSuffix = 11;</code>
     */
    public Builder setHashSuffix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hashSuffix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string HashSuffix = 11;</code>
     */
    public Builder clearHashSuffix() {
      
      hashSuffix_ = getDefaultInstance().getHashSuffix();
      onChanged();
      return this;
    }
    /**
     * <code>string HashSuffix = 11;</code>
     */
    public Builder setHashSuffixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hashSuffix_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.Repository)
  }

  // @@protoc_insertion_point(class_scope:utils.Repository)
  private static final net.anysync.protoc.Repository DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.Repository();
  }

  public static net.anysync.protoc.Repository getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Repository>
      PARSER = new com.google.protobuf.AbstractParser<Repository>() {
    public Repository parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Repository(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Repository> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Repository> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.Repository getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

