// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.ServerSyncResponse}
 */
public  final class ServerSyncResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.ServerSyncResponse)
    ServerSyncResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerSyncResponse.newBuilder() to construct.
  private ServerSyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerSyncResponse() {
    tasks_ = java.util.Collections.emptyList();
    taskTopFolder_ = "";
    code_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerSyncResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              props_ = com.google.protobuf.MapField.newMapField(
                  PropsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            props__ = input.readMessage(
                PropsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            props_.getMutableMap().put(
                props__.getKey(), props__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              folderUpdates_ = com.google.protobuf.MapField.newMapField(
                  FolderUpdatesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
            folderUpdates__ = input.readMessage(
                FolderUpdatesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            folderUpdates_.getMutableMap().put(
                folderUpdates__.getKey(), folderUpdates__.getValue());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tasks_ = new java.util.ArrayList<net.anysync.protoc.WriteTask>();
              mutable_bitField0_ |= 0x00000004;
            }
            tasks_.add(
                input.readMessage(net.anysync.protoc.WriteTask.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            taskTopFolder_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              objects_ = com.google.protobuf.MapField.newMapField(
                  ObjectsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            objects__ = input.readMessage(
                ObjectsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            objects_.getMutableMap().put(
                objects__.getKey(), objects__.getValue());
            break;
          }
          case 48: {

            code_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        tasks_ = java.util.Collections.unmodifiableList(tasks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetProps();
      case 2:
        return internalGetFolderUpdates();
      case 5:
        return internalGetObjects();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.ServerSyncResponse.class, net.anysync.protoc.ServerSyncResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROPS_FIELD_NUMBER = 1;
  private static final class PropsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_PropsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> props_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetProps() {
    if (props_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PropsDefaultEntryHolder.defaultEntry);
    }
    return props_;
  }

  public int getPropsCount() {
    return internalGetProps().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  public boolean containsProps(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetProps().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPropsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getProps() {
    return getPropsMap();
  }
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getPropsMap() {
    return internalGetProps().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  public java.lang.String getPropsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProps().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  public java.lang.String getPropsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProps().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int FOLDERUPDATES_FIELD_NUMBER = 2;
  private static final class FolderUpdatesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, net.anysync.protoc.ServerFolderUpdates> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, net.anysync.protoc.ServerFolderUpdates>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_FolderUpdatesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                net.anysync.protoc.ServerFolderUpdates.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, net.anysync.protoc.ServerFolderUpdates> folderUpdates_;
  private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  internalGetFolderUpdates() {
    if (folderUpdates_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FolderUpdatesDefaultEntryHolder.defaultEntry);
    }
    return folderUpdates_;
  }

  public int getFolderUpdatesCount() {
    return internalGetFolderUpdates().getMap().size();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  public boolean containsFolderUpdates(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetFolderUpdates().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFolderUpdatesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdates() {
    return getFolderUpdatesMap();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdatesMap() {
    return internalGetFolderUpdates().getMap();
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ServerFolderUpdates defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
        internalGetFolderUpdates().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
        internalGetFolderUpdates().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TASKS_FIELD_NUMBER = 3;
  private java.util.List<net.anysync.protoc.WriteTask> tasks_;
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  public java.util.List<net.anysync.protoc.WriteTask> getTasksList() {
    return tasks_;
  }
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  public java.util.List<? extends net.anysync.protoc.WriteTaskOrBuilder> 
      getTasksOrBuilderList() {
    return tasks_;
  }
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  public int getTasksCount() {
    return tasks_.size();
  }
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  public net.anysync.protoc.WriteTask getTasks(int index) {
    return tasks_.get(index);
  }
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  public net.anysync.protoc.WriteTaskOrBuilder getTasksOrBuilder(
      int index) {
    return tasks_.get(index);
  }

  public static final int TASKTOPFOLDER_FIELD_NUMBER = 4;
  private volatile java.lang.Object taskTopFolder_;
  /**
   * <code>string TaskTopFolder = 4;</code>
   */
  public java.lang.String getTaskTopFolder() {
    java.lang.Object ref = taskTopFolder_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskTopFolder_ = s;
      return s;
    }
  }
  /**
   * <code>string TaskTopFolder = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTaskTopFolderBytes() {
    java.lang.Object ref = taskTopFolder_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskTopFolder_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECTS_FIELD_NUMBER = 5;
  private static final class ObjectsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_ObjectsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> objects_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetObjects() {
    if (objects_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ObjectsDefaultEntryHolder.defaultEntry);
    }
    return objects_;
  }

  public int getObjectsCount() {
    return internalGetObjects().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  public boolean containsObjects(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetObjects().getMap().containsKey(key);
  }
  /**
   * Use {@link #getObjectsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjects() {
    return getObjectsMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjectsMap() {
    return internalGetObjects().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  public com.google.protobuf.ByteString getObjectsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetObjects().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  public com.google.protobuf.ByteString getObjectsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetObjects().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CODE_FIELD_NUMBER = 6;
  private int code_;
  /**
   * <code>int32 Code = 6;</code>
   */
  public int getCode() {
    return code_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProps(),
        PropsDefaultEntryHolder.defaultEntry,
        1);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFolderUpdates(),
        FolderUpdatesDefaultEntryHolder.defaultEntry,
        2);
    for (int i = 0; i < tasks_.size(); i++) {
      output.writeMessage(3, tasks_.get(i));
    }
    if (!getTaskTopFolderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, taskTopFolder_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetObjects(),
        ObjectsDefaultEntryHolder.defaultEntry,
        5);
    if (code_ != 0) {
      output.writeInt32(6, code_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetProps().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      props__ = PropsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, props__);
    }
    for (java.util.Map.Entry<java.lang.String, net.anysync.protoc.ServerFolderUpdates> entry
         : internalGetFolderUpdates().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
      folderUpdates__ = FolderUpdatesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, folderUpdates__);
    }
    for (int i = 0; i < tasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tasks_.get(i));
    }
    if (!getTaskTopFolderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, taskTopFolder_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetObjects().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      objects__ = ObjectsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, objects__);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, code_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.ServerSyncResponse)) {
      return super.equals(obj);
    }
    net.anysync.protoc.ServerSyncResponse other = (net.anysync.protoc.ServerSyncResponse) obj;

    boolean result = true;
    result = result && internalGetProps().equals(
        other.internalGetProps());
    result = result && internalGetFolderUpdates().equals(
        other.internalGetFolderUpdates());
    result = result && getTasksList()
        .equals(other.getTasksList());
    result = result && getTaskTopFolder()
        .equals(other.getTaskTopFolder());
    result = result && internalGetObjects().equals(
        other.internalGetObjects());
    result = result && (getCode()
        == other.getCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetProps().getMap().isEmpty()) {
      hash = (37 * hash) + PROPS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProps().hashCode();
    }
    if (!internalGetFolderUpdates().getMap().isEmpty()) {
      hash = (37 * hash) + FOLDERUPDATES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFolderUpdates().hashCode();
    }
    if (getTasksCount() > 0) {
      hash = (37 * hash) + TASKS_FIELD_NUMBER;
      hash = (53 * hash) + getTasksList().hashCode();
    }
    hash = (37 * hash) + TASKTOPFOLDER_FIELD_NUMBER;
    hash = (53 * hash) + getTaskTopFolder().hashCode();
    if (!internalGetObjects().getMap().isEmpty()) {
      hash = (37 * hash) + OBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetObjects().hashCode();
    }
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ServerSyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ServerSyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.ServerSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.ServerSyncResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.ServerSyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.ServerSyncResponse)
      net.anysync.protoc.ServerSyncResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetProps();
        case 2:
          return internalGetFolderUpdates();
        case 5:
          return internalGetObjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableProps();
        case 2:
          return internalGetMutableFolderUpdates();
        case 5:
          return internalGetMutableObjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.ServerSyncResponse.class, net.anysync.protoc.ServerSyncResponse.Builder.class);
    }

    // Construct using net.anysync.protoc.ServerSyncResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTasksFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableProps().clear();
      internalGetMutableFolderUpdates().clear();
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        tasksBuilder_.clear();
      }
      taskTopFolder_ = "";

      internalGetMutableObjects().clear();
      code_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_ServerSyncResponse_descriptor;
    }

    public net.anysync.protoc.ServerSyncResponse getDefaultInstanceForType() {
      return net.anysync.protoc.ServerSyncResponse.getDefaultInstance();
    }

    public net.anysync.protoc.ServerSyncResponse build() {
      net.anysync.protoc.ServerSyncResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.ServerSyncResponse buildPartial() {
      net.anysync.protoc.ServerSyncResponse result = new net.anysync.protoc.ServerSyncResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.props_ = internalGetProps();
      result.props_.makeImmutable();
      result.folderUpdates_ = internalGetFolderUpdates();
      result.folderUpdates_.makeImmutable();
      if (tasksBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tasks_ = java.util.Collections.unmodifiableList(tasks_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tasks_ = tasks_;
      } else {
        result.tasks_ = tasksBuilder_.build();
      }
      result.taskTopFolder_ = taskTopFolder_;
      result.objects_ = internalGetObjects();
      result.objects_.makeImmutable();
      result.code_ = code_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.ServerSyncResponse) {
        return mergeFrom((net.anysync.protoc.ServerSyncResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.ServerSyncResponse other) {
      if (other == net.anysync.protoc.ServerSyncResponse.getDefaultInstance()) return this;
      internalGetMutableProps().mergeFrom(
          other.internalGetProps());
      internalGetMutableFolderUpdates().mergeFrom(
          other.internalGetFolderUpdates());
      if (tasksBuilder_ == null) {
        if (!other.tasks_.isEmpty()) {
          if (tasks_.isEmpty()) {
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTasksIsMutable();
            tasks_.addAll(other.tasks_);
          }
          onChanged();
        }
      } else {
        if (!other.tasks_.isEmpty()) {
          if (tasksBuilder_.isEmpty()) {
            tasksBuilder_.dispose();
            tasksBuilder_ = null;
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tasksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTasksFieldBuilder() : null;
          } else {
            tasksBuilder_.addAllMessages(other.tasks_);
          }
        }
      }
      if (!other.getTaskTopFolder().isEmpty()) {
        taskTopFolder_ = other.taskTopFolder_;
        onChanged();
      }
      internalGetMutableObjects().mergeFrom(
          other.internalGetObjects());
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.ServerSyncResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.ServerSyncResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> props_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProps() {
      if (props_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropsDefaultEntryHolder.defaultEntry);
      }
      return props_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableProps() {
      onChanged();;
      if (props_ == null) {
        props_ = com.google.protobuf.MapField.newMapField(
            PropsDefaultEntryHolder.defaultEntry);
      }
      if (!props_.isMutable()) {
        props_ = props_.copy();
      }
      return props_;
    }

    public int getPropsCount() {
      return internalGetProps().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public boolean containsProps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProps() {
      return getPropsMap();
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getPropsMap() {
      return internalGetProps().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public java.lang.String getPropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public java.lang.String getPropsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearProps() {
      internalGetMutableProps().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public Builder removeProps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProps().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableProps() {
      return internalGetMutableProps().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */
    public Builder putProps(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProps().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Props = 1;</code>
     */

    public Builder putAllProps(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableProps().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, net.anysync.protoc.ServerFolderUpdates> folderUpdates_;
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    internalGetFolderUpdates() {
      if (folderUpdates_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FolderUpdatesDefaultEntryHolder.defaultEntry);
      }
      return folderUpdates_;
    }
    private com.google.protobuf.MapField<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    internalGetMutableFolderUpdates() {
      onChanged();;
      if (folderUpdates_ == null) {
        folderUpdates_ = com.google.protobuf.MapField.newMapField(
            FolderUpdatesDefaultEntryHolder.defaultEntry);
      }
      if (!folderUpdates_.isMutable()) {
        folderUpdates_ = folderUpdates_.copy();
      }
      return folderUpdates_;
    }

    public int getFolderUpdatesCount() {
      return internalGetFolderUpdates().getMap().size();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public boolean containsFolderUpdates(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFolderUpdates().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFolderUpdatesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdates() {
      return getFolderUpdatesMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> getFolderUpdatesMap() {
      return internalGetFolderUpdates().getMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
        java.lang.String key,
        net.anysync.protoc.ServerFolderUpdates defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
          internalGetFolderUpdates().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> map =
          internalGetFolderUpdates().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFolderUpdates() {
      internalGetMutableFolderUpdates().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public Builder removeFolderUpdates(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFolderUpdates().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
    getMutableFolderUpdates() {
      return internalGetMutableFolderUpdates().getMutableMap();
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */
    public Builder putFolderUpdates(
        java.lang.String key,
        net.anysync.protoc.ServerFolderUpdates value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFolderUpdates().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
     */

    public Builder putAllFolderUpdates(
        java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates> values) {
      internalGetMutableFolderUpdates().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<net.anysync.protoc.WriteTask> tasks_ =
      java.util.Collections.emptyList();
    private void ensureTasksIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        tasks_ = new java.util.ArrayList<net.anysync.protoc.WriteTask>(tasks_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.WriteTask, net.anysync.protoc.WriteTask.Builder, net.anysync.protoc.WriteTaskOrBuilder> tasksBuilder_;

    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public java.util.List<net.anysync.protoc.WriteTask> getTasksList() {
      if (tasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tasks_);
      } else {
        return tasksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public int getTasksCount() {
      if (tasksBuilder_ == null) {
        return tasks_.size();
      } else {
        return tasksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public net.anysync.protoc.WriteTask getTasks(int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);
      } else {
        return tasksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder setTasks(
        int index, net.anysync.protoc.WriteTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.set(index, value);
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder setTasks(
        int index, net.anysync.protoc.WriteTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder addTasks(net.anysync.protoc.WriteTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder addTasks(
        int index, net.anysync.protoc.WriteTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(index, value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder addTasks(
        net.anysync.protoc.WriteTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder addTasks(
        int index, net.anysync.protoc.WriteTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder addAllTasks(
        java.lang.Iterable<? extends net.anysync.protoc.WriteTask> values) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tasks_);
        onChanged();
      } else {
        tasksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder clearTasks() {
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tasksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public Builder removeTasks(int index) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.remove(index);
        onChanged();
      } else {
        tasksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public net.anysync.protoc.WriteTask.Builder getTasksBuilder(
        int index) {
      return getTasksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public net.anysync.protoc.WriteTaskOrBuilder getTasksOrBuilder(
        int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);  } else {
        return tasksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public java.util.List<? extends net.anysync.protoc.WriteTaskOrBuilder> 
         getTasksOrBuilderList() {
      if (tasksBuilder_ != null) {
        return tasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tasks_);
      }
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public net.anysync.protoc.WriteTask.Builder addTasksBuilder() {
      return getTasksFieldBuilder().addBuilder(
          net.anysync.protoc.WriteTask.getDefaultInstance());
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public net.anysync.protoc.WriteTask.Builder addTasksBuilder(
        int index) {
      return getTasksFieldBuilder().addBuilder(
          index, net.anysync.protoc.WriteTask.getDefaultInstance());
    }
    /**
     * <code>repeated .utils.WriteTask Tasks = 3;</code>
     */
    public java.util.List<net.anysync.protoc.WriteTask.Builder> 
         getTasksBuilderList() {
      return getTasksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.anysync.protoc.WriteTask, net.anysync.protoc.WriteTask.Builder, net.anysync.protoc.WriteTaskOrBuilder> 
        getTasksFieldBuilder() {
      if (tasksBuilder_ == null) {
        tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.anysync.protoc.WriteTask, net.anysync.protoc.WriteTask.Builder, net.anysync.protoc.WriteTaskOrBuilder>(
                tasks_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        tasks_ = null;
      }
      return tasksBuilder_;
    }

    private java.lang.Object taskTopFolder_ = "";
    /**
     * <code>string TaskTopFolder = 4;</code>
     */
    public java.lang.String getTaskTopFolder() {
      java.lang.Object ref = taskTopFolder_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskTopFolder_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string TaskTopFolder = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTopFolderBytes() {
      java.lang.Object ref = taskTopFolder_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskTopFolder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string TaskTopFolder = 4;</code>
     */
    public Builder setTaskTopFolder(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskTopFolder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string TaskTopFolder = 4;</code>
     */
    public Builder clearTaskTopFolder() {
      
      taskTopFolder_ = getDefaultInstance().getTaskTopFolder();
      onChanged();
      return this;
    }
    /**
     * <code>string TaskTopFolder = 4;</code>
     */
    public Builder setTaskTopFolderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskTopFolder_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> objects_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetObjects() {
      if (objects_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ObjectsDefaultEntryHolder.defaultEntry);
      }
      return objects_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableObjects() {
      onChanged();;
      if (objects_ == null) {
        objects_ = com.google.protobuf.MapField.newMapField(
            ObjectsDefaultEntryHolder.defaultEntry);
      }
      if (!objects_.isMutable()) {
        objects_ = objects_.copy();
      }
      return objects_;
    }

    public int getObjectsCount() {
      return internalGetObjects().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public boolean containsObjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetObjects().getMap().containsKey(key);
    }
    /**
     * Use {@link #getObjectsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjects() {
      return getObjectsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getObjectsMap() {
      return internalGetObjects().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public com.google.protobuf.ByteString getObjectsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetObjects().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public com.google.protobuf.ByteString getObjectsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetObjects().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearObjects() {
      internalGetMutableObjects().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public Builder removeObjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableObjects().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableObjects() {
      return internalGetMutableObjects().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */
    public Builder putObjects(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableObjects().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Objects = 5;</code>
     */

    public Builder putAllObjects(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableObjects().getMutableMap()
          .putAll(values);
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 Code = 6;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 Code = 6;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Code = 6;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.ServerSyncResponse)
  }

  // @@protoc_insertion_point(class_scope:utils.ServerSyncResponse)
  private static final net.anysync.protoc.ServerSyncResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.ServerSyncResponse();
  }

  public static net.anysync.protoc.ServerSyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerSyncResponse>
      PARSER = new com.google.protobuf.AbstractParser<ServerSyncResponse>() {
    public ServerSyncResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerSyncResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerSyncResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerSyncResponse> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.ServerSyncResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

