// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface ServerSyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.ServerSyncResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */
  int getPropsCount();
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */
  boolean containsProps(
      java.lang.String key);
  /**
   * Use {@link #getPropsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProps();
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropsMap();
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  java.lang.String getPropsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; Props = 1;</code>
   */

  java.lang.String getPropsOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  int getFolderUpdatesCount();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  boolean containsFolderUpdates(
      java.lang.String key);
  /**
   * Use {@link #getFolderUpdatesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdates();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdatesMap();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ServerFolderUpdates defaultValue);
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  java.util.List<net.anysync.protoc.WriteTask> 
      getTasksList();
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  net.anysync.protoc.WriteTask getTasks(int index);
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  int getTasksCount();
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  java.util.List<? extends net.anysync.protoc.WriteTaskOrBuilder> 
      getTasksOrBuilderList();
  /**
   * <code>repeated .utils.WriteTask Tasks = 3;</code>
   */
  net.anysync.protoc.WriteTaskOrBuilder getTasksOrBuilder(
      int index);

  /**
   * <code>string TaskTopFolder = 4;</code>
   */
  java.lang.String getTaskTopFolder();
  /**
   * <code>string TaskTopFolder = 4;</code>
   */
  com.google.protobuf.ByteString
      getTaskTopFolderBytes();

  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */
  int getObjectsCount();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */
  boolean containsObjects(
      java.lang.String key);
  /**
   * Use {@link #getObjectsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getObjects();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getObjectsMap();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  com.google.protobuf.ByteString getObjectsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Objects = 5;</code>
   */

  com.google.protobuf.ByteString getObjectsOrThrow(
      java.lang.String key);

  /**
   * <code>int32 Code = 6;</code>
   */
  int getCode();
}
