// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface ShareFolderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.ShareFolder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Hash = 2;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string Hash = 2;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();

  /**
   * <code>string Includes = 3;</code>
   */
  java.lang.String getIncludes();
  /**
   * <code>string Includes = 3;</code>
   */
  com.google.protobuf.ByteString
      getIncludesBytes();

  /**
   * <code>string FolderHash = 4;</code>
   */
  java.lang.String getFolderHash();
  /**
   * <code>string FolderHash = 4;</code>
   */
  com.google.protobuf.ByteString
      getFolderHashBytes();

  /**
   * <code>string Owner = 5;</code>
   */
  java.lang.String getOwner();
  /**
   * <code>string Owner = 5;</code>
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>string HashSuffix = 6;</code>
   */
  java.lang.String getHashSuffix();
  /**
   * <code>string HashSuffix = 6;</code>
   */
  com.google.protobuf.ByteString
      getHashSuffixBytes();

  /**
   * <code>uint32 Expiry = 7;</code>
   */
  int getExpiry();

  /**
   * <code>uint32 Permission = 8;</code>
   */
  int getPermission();

  /**
   * <code>map&lt;string, string&gt; MemberKeys = 9;</code>
   */
  int getMemberKeysCount();
  /**
   * <code>map&lt;string, string&gt; MemberKeys = 9;</code>
   */
  boolean containsMemberKeys(
      java.lang.String key);
  /**
   * Use {@link #getMemberKeysMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMemberKeys();
  /**
   * <code>map&lt;string, string&gt; MemberKeys = 9;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMemberKeysMap();
  /**
   * <code>map&lt;string, string&gt; MemberKeys = 9;</code>
   */

  java.lang.String getMemberKeysOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; MemberKeys = 9;</code>
   */

  java.lang.String getMemberKeysOrThrow(
      java.lang.String key);

  /**
   * <code>uint32 EncryptionLevel = 10;</code>
   */
  int getEncryptionLevel();

  /**
   * <code>string ID = 11;</code>
   */
  java.lang.String getID();
  /**
   * <code>string ID = 11;</code>
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
