// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface UpdateDatTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.UpdateDatTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 Time = 1;</code>
   */
  int getTime();

  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  int getFolderUpdatesCount();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  boolean containsFolderUpdates(
      java.lang.String key);
  /**
   * Use {@link #getFolderUpdatesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdates();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */
  java.util.Map<java.lang.String, net.anysync.protoc.ServerFolderUpdates>
  getFolderUpdatesMap();
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrDefault(
      java.lang.String key,
      net.anysync.protoc.ServerFolderUpdates defaultValue);
  /**
   * <code>map&lt;string, .utils.ServerFolderUpdates&gt; FolderUpdates = 2;</code>
   */

  net.anysync.protoc.ServerFolderUpdates getFolderUpdatesOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, bytes&gt; Objects = 3;</code>
   */
  int getObjectsCount();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 3;</code>
   */
  boolean containsObjects(
      java.lang.String key);
  /**
   * Use {@link #getObjectsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getObjects();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 3;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getObjectsMap();
  /**
   * <code>map&lt;string, bytes&gt; Objects = 3;</code>
   */

  com.google.protobuf.ByteString getObjectsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Objects = 3;</code>
   */

  com.google.protobuf.ByteString getObjectsOrThrow(
      java.lang.String key);

  /**
   * <code>int32 ID = 4;</code>
   */
  int getID();

  /**
   * <code>int32 ShareState = 5;</code>
   */
  int getShareState();
}
