// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.UploadStagingTask}
 */
public  final class UploadStagingTask extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.UploadStagingTask)
    UploadStagingTaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadStagingTask.newBuilder() to construct.
  private UploadStagingTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadStagingTask() {
    shareState_ = 0;
    owner_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadStagingTask(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            net.anysync.protoc.ModifiedData.Builder subBuilder = null;
            if (msg_ != null) {
              subBuilder = msg_.toBuilder();
            }
            msg_ = input.readMessage(net.anysync.protoc.ModifiedData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(msg_);
              msg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            shareState_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            owner_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_UploadStagingTask_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_UploadStagingTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.UploadStagingTask.class, net.anysync.protoc.UploadStagingTask.Builder.class);
  }

  public static final int MSG_FIELD_NUMBER = 1;
  private net.anysync.protoc.ModifiedData msg_;
  /**
   * <code>.utils.ModifiedData Msg = 1;</code>
   */
  public boolean hasMsg() {
    return msg_ != null;
  }
  /**
   * <code>.utils.ModifiedData Msg = 1;</code>
   */
  public net.anysync.protoc.ModifiedData getMsg() {
    return msg_ == null ? net.anysync.protoc.ModifiedData.getDefaultInstance() : msg_;
  }
  /**
   * <code>.utils.ModifiedData Msg = 1;</code>
   */
  public net.anysync.protoc.ModifiedDataOrBuilder getMsgOrBuilder() {
    return getMsg();
  }

  public static final int SHARESTATE_FIELD_NUMBER = 2;
  private int shareState_;
  /**
   * <code>int32 ShareState = 2;</code>
   */
  public int getShareState() {
    return shareState_;
  }

  public static final int OWNER_FIELD_NUMBER = 3;
  private volatile java.lang.Object owner_;
  /**
   * <code>string owner = 3;</code>
   */
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <code>string owner = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msg_ != null) {
      output.writeMessage(1, getMsg());
    }
    if (shareState_ != 0) {
      output.writeInt32(2, shareState_);
    }
    if (!getOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, owner_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMsg());
    }
    if (shareState_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, shareState_);
    }
    if (!getOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, owner_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.UploadStagingTask)) {
      return super.equals(obj);
    }
    net.anysync.protoc.UploadStagingTask other = (net.anysync.protoc.UploadStagingTask) obj;

    boolean result = true;
    result = result && (hasMsg() == other.hasMsg());
    if (hasMsg()) {
      result = result && getMsg()
          .equals(other.getMsg());
    }
    result = result && (getShareState()
        == other.getShareState());
    result = result && getOwner()
        .equals(other.getOwner());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMsg()) {
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
    }
    hash = (37 * hash) + SHARESTATE_FIELD_NUMBER;
    hash = (53 * hash) + getShareState();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.UploadStagingTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.UploadStagingTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.UploadStagingTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.UploadStagingTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.UploadStagingTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.UploadStagingTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.UploadStagingTask)
      net.anysync.protoc.UploadStagingTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_UploadStagingTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_UploadStagingTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.UploadStagingTask.class, net.anysync.protoc.UploadStagingTask.Builder.class);
    }

    // Construct using net.anysync.protoc.UploadStagingTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (msgBuilder_ == null) {
        msg_ = null;
      } else {
        msg_ = null;
        msgBuilder_ = null;
      }
      shareState_ = 0;

      owner_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_UploadStagingTask_descriptor;
    }

    public net.anysync.protoc.UploadStagingTask getDefaultInstanceForType() {
      return net.anysync.protoc.UploadStagingTask.getDefaultInstance();
    }

    public net.anysync.protoc.UploadStagingTask build() {
      net.anysync.protoc.UploadStagingTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.UploadStagingTask buildPartial() {
      net.anysync.protoc.UploadStagingTask result = new net.anysync.protoc.UploadStagingTask(this);
      if (msgBuilder_ == null) {
        result.msg_ = msg_;
      } else {
        result.msg_ = msgBuilder_.build();
      }
      result.shareState_ = shareState_;
      result.owner_ = owner_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.UploadStagingTask) {
        return mergeFrom((net.anysync.protoc.UploadStagingTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.UploadStagingTask other) {
      if (other == net.anysync.protoc.UploadStagingTask.getDefaultInstance()) return this;
      if (other.hasMsg()) {
        mergeMsg(other.getMsg());
      }
      if (other.getShareState() != 0) {
        setShareState(other.getShareState());
      }
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.UploadStagingTask parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.UploadStagingTask) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private net.anysync.protoc.ModifiedData msg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.anysync.protoc.ModifiedData, net.anysync.protoc.ModifiedData.Builder, net.anysync.protoc.ModifiedDataOrBuilder> msgBuilder_;
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public boolean hasMsg() {
      return msgBuilder_ != null || msg_ != null;
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public net.anysync.protoc.ModifiedData getMsg() {
      if (msgBuilder_ == null) {
        return msg_ == null ? net.anysync.protoc.ModifiedData.getDefaultInstance() : msg_;
      } else {
        return msgBuilder_.getMessage();
      }
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public Builder setMsg(net.anysync.protoc.ModifiedData value) {
      if (msgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        msgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public Builder setMsg(
        net.anysync.protoc.ModifiedData.Builder builderForValue) {
      if (msgBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        msgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public Builder mergeMsg(net.anysync.protoc.ModifiedData value) {
      if (msgBuilder_ == null) {
        if (msg_ != null) {
          msg_ =
            net.anysync.protoc.ModifiedData.newBuilder(msg_).mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        msgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public Builder clearMsg() {
      if (msgBuilder_ == null) {
        msg_ = null;
        onChanged();
      } else {
        msg_ = null;
        msgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public net.anysync.protoc.ModifiedData.Builder getMsgBuilder() {
      
      onChanged();
      return getMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    public net.anysync.protoc.ModifiedDataOrBuilder getMsgOrBuilder() {
      if (msgBuilder_ != null) {
        return msgBuilder_.getMessageOrBuilder();
      } else {
        return msg_ == null ?
            net.anysync.protoc.ModifiedData.getDefaultInstance() : msg_;
      }
    }
    /**
     * <code>.utils.ModifiedData Msg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.anysync.protoc.ModifiedData, net.anysync.protoc.ModifiedData.Builder, net.anysync.protoc.ModifiedDataOrBuilder> 
        getMsgFieldBuilder() {
      if (msgBuilder_ == null) {
        msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.anysync.protoc.ModifiedData, net.anysync.protoc.ModifiedData.Builder, net.anysync.protoc.ModifiedDataOrBuilder>(
                getMsg(),
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      return msgBuilder_;
    }

    private int shareState_ ;
    /**
     * <code>int32 ShareState = 2;</code>
     */
    public int getShareState() {
      return shareState_;
    }
    /**
     * <code>int32 ShareState = 2;</code>
     */
    public Builder setShareState(int value) {
      
      shareState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ShareState = 2;</code>
     */
    public Builder clearShareState() {
      
      shareState_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object owner_ = "";
    /**
     * <code>string owner = 3;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner = 3;</code>
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      owner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner = 3;</code>
     */
    public Builder clearOwner() {
      
      owner_ = getDefaultInstance().getOwner();
      onChanged();
      return this;
    }
    /**
     * <code>string owner = 3;</code>
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      owner_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.UploadStagingTask)
  }

  // @@protoc_insertion_point(class_scope:utils.UploadStagingTask)
  private static final net.anysync.protoc.UploadStagingTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.UploadStagingTask();
  }

  public static net.anysync.protoc.UploadStagingTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadStagingTask>
      PARSER = new com.google.protobuf.AbstractParser<UploadStagingTask>() {
    public UploadStagingTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadStagingTask(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadStagingTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadStagingTask> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.UploadStagingTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

