// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface UserAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.UserAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ID = 1;</code>
   */
  int getID();

  /**
   * <code>int32 AccountType = 2;</code>
   */
  int getAccountType();

  /**
   * <code>int32 AccountRole = 3;</code>
   */
  int getAccountRole();

  /**
   * <code>string Organization = 4;</code>
   */
  java.lang.String getOrganization();
  /**
   * <code>string Organization = 4;</code>
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();

  /**
   * <code>string Group = 5;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string Group = 5;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string Email = 6;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string Name = 7;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bytes AccessToken = 8;</code>
   */
  com.google.protobuf.ByteString getAccessToken();

  /**
   * <code>int32 MaxID = 9;</code>
   */
  int getMaxID();

  /**
   * <code>uint32 LastLogin = 10;</code>
   */
  int getLastLogin();

  /**
   * <code>bytes AuthKey = 11;</code>
   */
  com.google.protobuf.ByteString getAuthKey();

  /**
   * <code>string Server = 12;</code>
   */
  java.lang.String getServer();
  /**
   * <code>string Server = 12;</code>
   */
  com.google.protobuf.ByteString
      getServerBytes();

  /**
   * <code>bytes PubKey = 13;</code>
   */
  com.google.protobuf.ByteString getPubKey();

  /**
   * <code>bytes RealAuthKey = 14;</code>
   */
  com.google.protobuf.ByteString getRealAuthKey();

  /**
   * <code>uint32 Register = 15;</code>
   */
  int getRegister();

  /**
   * <code>uint32 Quota = 16;</code>
   */
  int getQuota();

  /**
   * <code>string Phone = 17;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string Phone = 17;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string Bucket = 18;</code>
   */
  java.lang.String getBucket();
  /**
   * <code>string Bucket = 18;</code>
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>uint32 Expiry = 19;</code>
   */
  int getExpiry();

  /**
   * <code>string Prefix = 20;</code>
   */
  java.lang.String getPrefix();
  /**
   * <code>string Prefix = 20;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>string OrderID = 21;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string OrderID = 21;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>string OrderEmail = 22;</code>
   */
  java.lang.String getOrderEmail();
  /**
   * <code>string OrderEmail = 22;</code>
   */
  com.google.protobuf.ByteString
      getOrderEmailBytes();

  /**
   * <code>string OrderName = 23;</code>
   */
  java.lang.String getOrderName();
  /**
   * <code>string OrderName = 23;</code>
   */
  com.google.protobuf.ByteString
      getOrderNameBytes();

  /**
   * <code>string OrderPhone = 24;</code>
   */
  java.lang.String getOrderPhone();
  /**
   * <code>string OrderPhone = 24;</code>
   */
  com.google.protobuf.ByteString
      getOrderPhoneBytes();

  /**
   * <code>string OrderRef = 25;</code>
   */
  java.lang.String getOrderRef();
  /**
   * <code>string OrderRef = 25;</code>
   */
  com.google.protobuf.ByteString
      getOrderRefBytes();

  /**
   * <code>string OrderCompany = 26;</code>
   */
  java.lang.String getOrderCompany();
  /**
   * <code>string OrderCompany = 26;</code>
   */
  com.google.protobuf.ByteString
      getOrderCompanyBytes();

  /**
   * <code>uint32 OrderDate = 27;</code>
   */
  int getOrderDate();

  /**
   * <code>string OrderReferrer = 28;</code>
   */
  java.lang.String getOrderReferrer();
  /**
   * <code>string OrderReferrer = 28;</code>
   */
  com.google.protobuf.ByteString
      getOrderReferrerBytes();

  /**
   * <code>string LastIP = 29;</code>
   */
  java.lang.String getLastIP();
  /**
   * <code>string LastIP = 29;</code>
   */
  com.google.protobuf.ByteString
      getLastIPBytes();
}
