// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

/**
 * Protobuf type {@code utils.WriteTask}
 */
public  final class WriteTask extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:utils.WriteTask)
    WriteTaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WriteTask.newBuilder() to construct.
  private WriteTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WriteTask() {
    mode_ = 0;
    folderHash_ = "";
    index_ = 0;
    fileHash_ = "";
    data_ = "";
    side_ = 0;
    bytes_ = com.google.protobuf.ByteString.EMPTY;
    time_ = 0;
    iD_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WriteTask(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            mode_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            folderHash_ = s;
            break;
          }
          case 24: {

            index_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fileHash_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            data_ = s;
            break;
          }
          case 48: {

            side_ = input.readInt32();
            break;
          }
          case 58: {

            bytes_ = input.readBytes();
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              attribs_ = com.google.protobuf.MapField.newMapField(
                  AttribsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000080;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            attribs__ = input.readMessage(
                AttribsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attribs_.getMutableMap().put(
                attribs__.getKey(), attribs__.getValue());
            break;
          }
          case 72: {

            time_ = input.readUInt32();
            break;
          }
          case 80: {

            iD_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 8:
        return internalGetAttribs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.anysync.protoc.WriteTask.class, net.anysync.protoc.WriteTask.Builder.class);
  }

  private int bitField0_;
  public static final int MODE_FIELD_NUMBER = 1;
  private int mode_;
  /**
   * <code>uint32 Mode = 1;</code>
   */
  public int getMode() {
    return mode_;
  }

  public static final int FOLDERHASH_FIELD_NUMBER = 2;
  private volatile java.lang.Object folderHash_;
  /**
   * <code>string FolderHash = 2;</code>
   */
  public java.lang.String getFolderHash() {
    java.lang.Object ref = folderHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      folderHash_ = s;
      return s;
    }
  }
  /**
   * <code>string FolderHash = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFolderHashBytes() {
    java.lang.Object ref = folderHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      folderHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private int index_;
  /**
   * <code>uint32 Index = 3;</code>
   */
  public int getIndex() {
    return index_;
  }

  public static final int FILEHASH_FIELD_NUMBER = 4;
  private volatile java.lang.Object fileHash_;
  /**
   * <code>string FileHash = 4;</code>
   */
  public java.lang.String getFileHash() {
    java.lang.Object ref = fileHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileHash_ = s;
      return s;
    }
  }
  /**
   * <code>string FileHash = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFileHashBytes() {
    java.lang.Object ref = fileHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 5;
  private volatile java.lang.Object data_;
  /**
   * <code>string Data = 5;</code>
   */
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string Data = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIDE_FIELD_NUMBER = 6;
  private int side_;
  /**
   * <code>int32 Side = 6;</code>
   */
  public int getSide() {
    return side_;
  }

  public static final int BYTES_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString bytes_;
  /**
   * <code>bytes Bytes = 7;</code>
   */
  public com.google.protobuf.ByteString getBytes() {
    return bytes_;
  }

  public static final int ATTRIBS_FIELD_NUMBER = 8;
  private static final class AttribsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_AttribsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> attribs_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetAttribs() {
    if (attribs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttribsDefaultEntryHolder.defaultEntry);
    }
    return attribs_;
  }

  public int getAttribsCount() {
    return internalGetAttribs().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  public boolean containsAttribs(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttribs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttribsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getAttribs() {
    return getAttribsMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getAttribsMap() {
    return internalGetAttribs().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  public com.google.protobuf.ByteString getAttribsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetAttribs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  public com.google.protobuf.ByteString getAttribsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetAttribs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIME_FIELD_NUMBER = 9;
  private int time_;
  /**
   * <code>uint32 Time = 9;</code>
   */
  public int getTime() {
    return time_;
  }

  public static final int ID_FIELD_NUMBER = 10;
  private int iD_;
  /**
   * <code>int32 ID = 10;</code>
   */
  public int getID() {
    return iD_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mode_ != 0) {
      output.writeUInt32(1, mode_);
    }
    if (!getFolderHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, folderHash_);
    }
    if (index_ != 0) {
      output.writeUInt32(3, index_);
    }
    if (!getFileHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileHash_);
    }
    if (!getDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
    }
    if (side_ != 0) {
      output.writeInt32(6, side_);
    }
    if (!bytes_.isEmpty()) {
      output.writeBytes(7, bytes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttribs(),
        AttribsDefaultEntryHolder.defaultEntry,
        8);
    if (time_ != 0) {
      output.writeUInt32(9, time_);
    }
    if (iD_ != 0) {
      output.writeInt32(10, iD_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, mode_);
    }
    if (!getFolderHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, folderHash_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, index_);
    }
    if (!getFileHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileHash_);
    }
    if (!getDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
    }
    if (side_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, side_);
    }
    if (!bytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, bytes_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetAttribs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      attribs__ = AttribsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, attribs__);
    }
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, time_);
    }
    if (iD_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, iD_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.anysync.protoc.WriteTask)) {
      return super.equals(obj);
    }
    net.anysync.protoc.WriteTask other = (net.anysync.protoc.WriteTask) obj;

    boolean result = true;
    result = result && (getMode()
        == other.getMode());
    result = result && getFolderHash()
        .equals(other.getFolderHash());
    result = result && (getIndex()
        == other.getIndex());
    result = result && getFileHash()
        .equals(other.getFileHash());
    result = result && getData()
        .equals(other.getData());
    result = result && (getSide()
        == other.getSide());
    result = result && getBytes()
        .equals(other.getBytes());
    result = result && internalGetAttribs().equals(
        other.internalGetAttribs());
    result = result && (getTime()
        == other.getTime());
    result = result && (getID()
        == other.getID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode();
    hash = (37 * hash) + FOLDERHASH_FIELD_NUMBER;
    hash = (53 * hash) + getFolderHash().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + FILEHASH_FIELD_NUMBER;
    hash = (53 * hash) + getFileHash().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + getSide();
    hash = (37 * hash) + BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBytes().hashCode();
    if (!internalGetAttribs().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttribs().hashCode();
    }
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.anysync.protoc.WriteTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.WriteTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.anysync.protoc.WriteTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.WriteTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.WriteTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.anysync.protoc.WriteTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.anysync.protoc.WriteTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code utils.WriteTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:utils.WriteTask)
      net.anysync.protoc.WriteTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetAttribs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableAttribs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.anysync.protoc.WriteTask.class, net.anysync.protoc.WriteTask.Builder.class);
    }

    // Construct using net.anysync.protoc.WriteTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mode_ = 0;

      folderHash_ = "";

      index_ = 0;

      fileHash_ = "";

      data_ = "";

      side_ = 0;

      bytes_ = com.google.protobuf.ByteString.EMPTY;

      internalGetMutableAttribs().clear();
      time_ = 0;

      iD_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.anysync.protoc.ProtoBufData.internal_static_utils_WriteTask_descriptor;
    }

    public net.anysync.protoc.WriteTask getDefaultInstanceForType() {
      return net.anysync.protoc.WriteTask.getDefaultInstance();
    }

    public net.anysync.protoc.WriteTask build() {
      net.anysync.protoc.WriteTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.anysync.protoc.WriteTask buildPartial() {
      net.anysync.protoc.WriteTask result = new net.anysync.protoc.WriteTask(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.mode_ = mode_;
      result.folderHash_ = folderHash_;
      result.index_ = index_;
      result.fileHash_ = fileHash_;
      result.data_ = data_;
      result.side_ = side_;
      result.bytes_ = bytes_;
      result.attribs_ = internalGetAttribs();
      result.attribs_.makeImmutable();
      result.time_ = time_;
      result.iD_ = iD_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.anysync.protoc.WriteTask) {
        return mergeFrom((net.anysync.protoc.WriteTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.anysync.protoc.WriteTask other) {
      if (other == net.anysync.protoc.WriteTask.getDefaultInstance()) return this;
      if (other.getMode() != 0) {
        setMode(other.getMode());
      }
      if (!other.getFolderHash().isEmpty()) {
        folderHash_ = other.folderHash_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getFileHash().isEmpty()) {
        fileHash_ = other.fileHash_;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        onChanged();
      }
      if (other.getSide() != 0) {
        setSide(other.getSide());
      }
      if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
        setBytes(other.getBytes());
      }
      internalGetMutableAttribs().mergeFrom(
          other.internalGetAttribs());
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (other.getID() != 0) {
        setID(other.getID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.anysync.protoc.WriteTask parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.anysync.protoc.WriteTask) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int mode_ ;
    /**
     * <code>uint32 Mode = 1;</code>
     */
    public int getMode() {
      return mode_;
    }
    /**
     * <code>uint32 Mode = 1;</code>
     */
    public Builder setMode(int value) {
      
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Mode = 1;</code>
     */
    public Builder clearMode() {
      
      mode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object folderHash_ = "";
    /**
     * <code>string FolderHash = 2;</code>
     */
    public java.lang.String getFolderHash() {
      java.lang.Object ref = folderHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        folderHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string FolderHash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFolderHashBytes() {
      java.lang.Object ref = folderHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        folderHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string FolderHash = 2;</code>
     */
    public Builder setFolderHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      folderHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string FolderHash = 2;</code>
     */
    public Builder clearFolderHash() {
      
      folderHash_ = getDefaultInstance().getFolderHash();
      onChanged();
      return this;
    }
    /**
     * <code>string FolderHash = 2;</code>
     */
    public Builder setFolderHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      folderHash_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <code>uint32 Index = 3;</code>
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 Index = 3;</code>
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Index = 3;</code>
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fileHash_ = "";
    /**
     * <code>string FileHash = 4;</code>
     */
    public java.lang.String getFileHash() {
      java.lang.Object ref = fileHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string FileHash = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFileHashBytes() {
      java.lang.Object ref = fileHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string FileHash = 4;</code>
     */
    public Builder setFileHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string FileHash = 4;</code>
     */
    public Builder clearFileHash() {
      
      fileHash_ = getDefaultInstance().getFileHash();
      onChanged();
      return this;
    }
    /**
     * <code>string FileHash = 4;</code>
     */
    public Builder setFileHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileHash_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string Data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Data = 5;</code>
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Data = 5;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>string Data = 5;</code>
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      data_ = value;
      onChanged();
      return this;
    }

    private int side_ ;
    /**
     * <code>int32 Side = 6;</code>
     */
    public int getSide() {
      return side_;
    }
    /**
     * <code>int32 Side = 6;</code>
     */
    public Builder setSide(int value) {
      
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Side = 6;</code>
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes Bytes = 7;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes Bytes = 7;</code>
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes Bytes = 7;</code>
     */
    public Builder clearBytes() {
      
      bytes_ = getDefaultInstance().getBytes();
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> attribs_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetAttribs() {
      if (attribs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttribsDefaultEntryHolder.defaultEntry);
      }
      return attribs_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableAttribs() {
      onChanged();;
      if (attribs_ == null) {
        attribs_ = com.google.protobuf.MapField.newMapField(
            AttribsDefaultEntryHolder.defaultEntry);
      }
      if (!attribs_.isMutable()) {
        attribs_ = attribs_.copy();
      }
      return attribs_;
    }

    public int getAttribsCount() {
      return internalGetAttribs().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public boolean containsAttribs(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttribs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttribsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getAttribs() {
      return getAttribsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getAttribsMap() {
      return internalGetAttribs().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public com.google.protobuf.ByteString getAttribsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetAttribs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public com.google.protobuf.ByteString getAttribsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetAttribs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttribs() {
      internalGetMutableAttribs().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public Builder removeAttribs(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttribs().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableAttribs() {
      return internalGetMutableAttribs().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */
    public Builder putAttribs(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttribs().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
     */

    public Builder putAllAttribs(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableAttribs().getMutableMap()
          .putAll(values);
      return this;
    }

    private int time_ ;
    /**
     * <code>uint32 Time = 9;</code>
     */
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 Time = 9;</code>
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 Time = 9;</code>
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private int iD_ ;
    /**
     * <code>int32 ID = 10;</code>
     */
    public int getID() {
      return iD_;
    }
    /**
     * <code>int32 ID = 10;</code>
     */
    public Builder setID(int value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ID = 10;</code>
     */
    public Builder clearID() {
      
      iD_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:utils.WriteTask)
  }

  // @@protoc_insertion_point(class_scope:utils.WriteTask)
  private static final net.anysync.protoc.WriteTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.anysync.protoc.WriteTask();
  }

  public static net.anysync.protoc.WriteTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WriteTask>
      PARSER = new com.google.protobuf.AbstractParser<WriteTask>() {
    public WriteTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WriteTask(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WriteTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WriteTask> getParserForType() {
    return PARSER;
  }

  public net.anysync.protoc.WriteTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

