// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rescan.proto

package net.anysync.protoc;

public interface WriteTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:utils.WriteTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 Mode = 1;</code>
   */
  int getMode();

  /**
   * <code>string FolderHash = 2;</code>
   */
  java.lang.String getFolderHash();
  /**
   * <code>string FolderHash = 2;</code>
   */
  com.google.protobuf.ByteString
      getFolderHashBytes();

  /**
   * <code>uint32 Index = 3;</code>
   */
  int getIndex();

  /**
   * <code>string FileHash = 4;</code>
   */
  java.lang.String getFileHash();
  /**
   * <code>string FileHash = 4;</code>
   */
  com.google.protobuf.ByteString
      getFileHashBytes();

  /**
   * <code>string Data = 5;</code>
   */
  java.lang.String getData();
  /**
   * <code>string Data = 5;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>int32 Side = 6;</code>
   */
  int getSide();

  /**
   * <code>bytes Bytes = 7;</code>
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */
  int getAttribsCount();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */
  boolean containsAttribs(
      java.lang.String key);
  /**
   * Use {@link #getAttribsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getAttribs();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getAttribsMap();
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  com.google.protobuf.ByteString getAttribsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; Attribs = 8;</code>
   */

  com.google.protobuf.ByteString getAttribsOrThrow(
      java.lang.String key);

  /**
   * <code>uint32 Time = 9;</code>
   */
  int getTime();

  /**
   * <code>int32 ID = 10;</code>
   */
  int getID();
}
